// Code generated by protoc-gen-go. DO NOT EDIT.
// source: req.proto

package mproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CLIENT REQ : MSG_ID 0
// 1.PING
type PING struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PING) Reset()         { *m = PING{} }
func (m *PING) String() string { return proto.CompactTextString(m) }
func (*PING) ProtoMessage()    {}
func (*PING) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{0}
}

func (m *PING) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PING.Unmarshal(m, b)
}
func (m *PING) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PING.Marshal(b, m, deterministic)
}
func (m *PING) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PING.Merge(m, src)
}
func (m *PING) XXX_Size() int {
	return xxx_messageInfo_PING.Size(m)
}
func (m *PING) XXX_DiscardUnknown() {
	xxx_messageInfo_PING.DiscardUnknown(m)
}

var xxx_messageInfo_PING proto.InternalMessageInfo

func (m *PING) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// CLIENT REQ : MSG_ID 100
// 1.登录请求
type ReqLogin struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserPassword         string   `protobuf:"bytes,2,opt,name=userPassword,proto3" json:"userPassword,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{1}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ReqLogin) GetUserPassword() string {
	if m != nil {
		return m.UserPassword
	}
	return ""
}

func (m *ReqLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// CLIENT REQ : MSG_ID 101
// 2.进入房间
type ReqEnterRoom struct {
	//
	//ExperienceField int32 = 1 // 体验场
	//LowField        int32 = 2 // 初级场
	//MidField        int32 = 3 // 中级场
	//HighField       int32 = 4 // 高级场
	RoomType             int32    `protobuf:"varint,1,opt,name=roomType,proto3" json:"roomType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqEnterRoom) Reset()         { *m = ReqEnterRoom{} }
func (m *ReqEnterRoom) String() string { return proto.CompactTextString(m) }
func (*ReqEnterRoom) ProtoMessage()    {}
func (*ReqEnterRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{2}
}

func (m *ReqEnterRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEnterRoom.Unmarshal(m, b)
}
func (m *ReqEnterRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEnterRoom.Marshal(b, m, deterministic)
}
func (m *ReqEnterRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEnterRoom.Merge(m, src)
}
func (m *ReqEnterRoom) XXX_Size() int {
	return xxx_messageInfo_ReqEnterRoom.Size(m)
}
func (m *ReqEnterRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEnterRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEnterRoom proto.InternalMessageInfo

func (m *ReqEnterRoom) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

// SERVER PUSH : MSG_ID 102  // 抢地主阶段
// 3.抢地主阶段
type ReqGetLandlordDo struct {
	Action               int32    `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetLandlordDo) Reset()         { *m = ReqGetLandlordDo{} }
func (m *ReqGetLandlordDo) String() string { return proto.CompactTextString(m) }
func (*ReqGetLandlordDo) ProtoMessage()    {}
func (*ReqGetLandlordDo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{3}
}

func (m *ReqGetLandlordDo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetLandlordDo.Unmarshal(m, b)
}
func (m *ReqGetLandlordDo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetLandlordDo.Marshal(b, m, deterministic)
}
func (m *ReqGetLandlordDo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetLandlordDo.Merge(m, src)
}
func (m *ReqGetLandlordDo) XXX_Size() int {
	return xxx_messageInfo_ReqGetLandlordDo.Size(m)
}
func (m *ReqGetLandlordDo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetLandlordDo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetLandlordDo proto.InternalMessageInfo

func (m *ReqGetLandlordDo) GetAction() int32 {
	if m != nil {
		return m.Action
	}
	return 0
}

// SERVER PUSH : MSG_ID 103  // 出牌
// 3.出牌
type ReqOutCardDo struct {
	Action               int32    `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	Cards                []*Card  `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqOutCardDo) Reset()         { *m = ReqOutCardDo{} }
func (m *ReqOutCardDo) String() string { return proto.CompactTextString(m) }
func (*ReqOutCardDo) ProtoMessage()    {}
func (*ReqOutCardDo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{4}
}

func (m *ReqOutCardDo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqOutCardDo.Unmarshal(m, b)
}
func (m *ReqOutCardDo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqOutCardDo.Marshal(b, m, deterministic)
}
func (m *ReqOutCardDo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqOutCardDo.Merge(m, src)
}
func (m *ReqOutCardDo) XXX_Size() int {
	return xxx_messageInfo_ReqOutCardDo.Size(m)
}
func (m *ReqOutCardDo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqOutCardDo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqOutCardDo proto.InternalMessageInfo

func (m *ReqOutCardDo) GetAction() int32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ReqOutCardDo) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

// SERVER PUSH : MSG_ID 104  // 退出房间
// 1.退出房间
type ReqExitRoom struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqExitRoom) Reset()         { *m = ReqExitRoom{} }
func (m *ReqExitRoom) String() string { return proto.CompactTextString(m) }
func (*ReqExitRoom) ProtoMessage()    {}
func (*ReqExitRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{5}
}

func (m *ReqExitRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqExitRoom.Unmarshal(m, b)
}
func (m *ReqExitRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqExitRoom.Marshal(b, m, deterministic)
}
func (m *ReqExitRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqExitRoom.Merge(m, src)
}
func (m *ReqExitRoom) XXX_Size() int {
	return xxx_messageInfo_ReqExitRoom.Size(m)
}
func (m *ReqExitRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqExitRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ReqExitRoom proto.InternalMessageInfo

func (m *ReqExitRoom) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

// SERVER PUSH : MSG_ID 105  // 退出房间
// 5.托管请求
type ReqGameHosting struct {
	GameHostType         int32    `protobuf:"varint,1,opt,name=GameHostType,proto3" json:"GameHostType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGameHosting) Reset()         { *m = ReqGameHosting{} }
func (m *ReqGameHosting) String() string { return proto.CompactTextString(m) }
func (*ReqGameHosting) ProtoMessage()    {}
func (*ReqGameHosting) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{6}
}

func (m *ReqGameHosting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGameHosting.Unmarshal(m, b)
}
func (m *ReqGameHosting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGameHosting.Marshal(b, m, deterministic)
}
func (m *ReqGameHosting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGameHosting.Merge(m, src)
}
func (m *ReqGameHosting) XXX_Size() int {
	return xxx_messageInfo_ReqGameHosting.Size(m)
}
func (m *ReqGameHosting) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGameHosting.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGameHosting proto.InternalMessageInfo

func (m *ReqGameHosting) GetGameHostType() int32 {
	if m != nil {
		return m.GameHostType
	}
	return 0
}

// CLIENT REQ : MSG_ID 106
// 6.进入房间 检查是否能进
type ReqEnterRoomCheck struct {
	RoomType             int32    `protobuf:"varint,1,opt,name=roomType,proto3" json:"roomType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqEnterRoomCheck) Reset()         { *m = ReqEnterRoomCheck{} }
func (m *ReqEnterRoomCheck) String() string { return proto.CompactTextString(m) }
func (*ReqEnterRoomCheck) ProtoMessage()    {}
func (*ReqEnterRoomCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{7}
}

func (m *ReqEnterRoomCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEnterRoomCheck.Unmarshal(m, b)
}
func (m *ReqEnterRoomCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEnterRoomCheck.Marshal(b, m, deterministic)
}
func (m *ReqEnterRoomCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEnterRoomCheck.Merge(m, src)
}
func (m *ReqEnterRoomCheck) XXX_Size() int {
	return xxx_messageInfo_ReqEnterRoomCheck.Size(m)
}
func (m *ReqEnterRoomCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEnterRoomCheck.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEnterRoomCheck proto.InternalMessageInfo

func (m *ReqEnterRoomCheck) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func init() {
	proto.RegisterType((*PING)(nil), "mproto.PING")
	proto.RegisterType((*ReqLogin)(nil), "mproto.ReqLogin")
	proto.RegisterType((*ReqEnterRoom)(nil), "mproto.ReqEnterRoom")
	proto.RegisterType((*ReqGetLandlordDo)(nil), "mproto.ReqGetLandlordDo")
	proto.RegisterType((*ReqOutCardDo)(nil), "mproto.ReqOutCardDo")
	proto.RegisterType((*ReqExitRoom)(nil), "mproto.ReqExitRoom")
	proto.RegisterType((*ReqGameHosting)(nil), "mproto.ReqGameHosting")
	proto.RegisterType((*ReqEnterRoomCheck)(nil), "mproto.ReqEnterRoomCheck")
}

func init() { proto.RegisterFile("req.proto", fileDescriptor_a52bd445c288993d) }

var fileDescriptor_a52bd445c288993d = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0x87, 0xd9, 0x9f, 0x96, 0xed, 0x6c, 0xbc, 0xbc, 0x06, 0x19, 0xa5, 0x57, 0x23, 0x20, 0x8c,
	0x5d, 0x54, 0x50, 0xbf, 0xc1, 0x94, 0x39, 0x19, 0x3a, 0x82, 0x97, 0xde, 0xc4, 0xf6, 0x30, 0xcb,
	0x6c, 0x4e, 0x9b, 0x64, 0xa8, 0xdf, 0x5e, 0x92, 0x4c, 0xed, 0xbc, 0xf0, 0xaa, 0xe7, 0x39, 0xe7,
	0x34, 0x79, 0xf2, 0x83, 0xa1, 0xc6, 0x26, 0xab, 0x35, 0x59, 0x62, 0x71, 0xe5, 0xbf, 0x29, 0x68,
	0x34, 0x75, 0xe8, 0xf1, 0x14, 0xfa, 0x9b, 0xd5, 0xfd, 0x92, 0x31, 0xe8, 0xdb, 0xb2, 0xc2, 0xa4,
	0x33, 0xed, 0xcc, 0x7a, 0xc2, 0xd7, 0xfc, 0x09, 0x06, 0x02, 0x9b, 0x35, 0x6d, 0x4b, 0xc5, 0x26,
	0x10, 0xef, 0x0d, 0xea, 0x55, 0xe1, 0x37, 0x86, 0xe2, 0x40, 0x8c, 0xc3, 0xd8, 0x55, 0x1b, 0x69,
	0xcc, 0x1b, 0xe9, 0x22, 0xe9, 0xfa, 0xe9, 0x51, 0x8f, 0x9d, 0x42, 0x64, 0x69, 0x87, 0x2a, 0xe9,
	0xf9, 0x61, 0x00, 0x3e, 0x87, 0xb1, 0xc0, 0xe6, 0x46, 0x59, 0xd4, 0x82, 0xa8, 0x62, 0x29, 0x0c,
	0x34, 0x51, 0xf5, 0xf8, 0x51, 0x07, 0x8b, 0x48, 0x7c, 0x33, 0x9f, 0xc3, 0x7f, 0x81, 0xcd, 0x12,
	0xed, 0x5a, 0xaa, 0xe2, 0x95, 0x74, 0x71, 0x4d, 0xce, 0x48, 0xe6, 0xb6, 0x24, 0xe5, 0xef, 0x8c,
	0xc4, 0x81, 0xf8, 0x9d, 0x3f, 0xf7, 0x61, 0x6f, 0x17, 0xf2, 0xd7, 0x5e, 0xa7, 0xbd, 0xc7, 0x38,
	0x44, 0xb9, 0xd4, 0x85, 0x49, 0xba, 0xd3, 0xde, 0x6c, 0x74, 0x31, 0xce, 0x42, 0x3a, 0x99, 0xfb,
	0x4d, 0x84, 0x11, 0x3f, 0x83, 0x91, 0x73, 0x7c, 0x2f, 0xad, 0x57, 0x9c, 0x40, 0xec, 0x94, 0x7e,
	0x42, 0x08, 0xc4, 0xaf, 0xe0, 0x9f, 0xd3, 0x93, 0x15, 0xde, 0x92, 0xb1, 0xa5, 0xda, 0xba, 0x58,
	0xbe, 0xb0, 0xf5, 0xa0, 0xa3, 0x1e, 0x3f, 0x87, 0x93, 0x76, 0x00, 0x8b, 0x17, 0xcc, 0x77, 0x7f,
	0xa5, 0xf0, 0x1c, 0x7b, 0xc1, 0xcb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x17, 0x49, 0xfc,
	0xd3, 0x01, 0x00, 0x00,
}
