// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resp.proto

package mproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// =================================  SERVER 收到指令返回 200 pong 消息为1 开始 ===========
// SERVER RESP : MSG_ID 1
// 1.PONG
type PONG struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PONG) Reset()         { *m = PONG{} }
func (m *PONG) String() string { return proto.CompactTextString(m) }
func (*PONG) ProtoMessage()    {}
func (*PONG) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{0}
}

func (m *PONG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PONG.Unmarshal(m, b)
}
func (m *PONG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PONG.Marshal(b, m, deterministic)
}
func (m *PONG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PONG.Merge(m, src)
}
func (m *PONG) XXX_Size() int {
	return xxx_messageInfo_PONG.Size(m)
}
func (m *PONG) XXX_DiscardUnknown() {
	xxx_messageInfo_PONG.DiscardUnknown(m)
}

var xxx_messageInfo_PONG proto.InternalMessageInfo

func (m *PONG) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// SERVER RESP : MSG_ID 200
// 1.登录返回
type RespLogin struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RespLogin) Reset()         { *m = RespLogin{} }
func (m *RespLogin) String() string { return proto.CompactTextString(m) }
func (*RespLogin) ProtoMessage()    {}
func (*RespLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{1}
}

func (m *RespLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespLogin.Unmarshal(m, b)
}
func (m *RespLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespLogin.Marshal(b, m, deterministic)
}
func (m *RespLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespLogin.Merge(m, src)
}
func (m *RespLogin) XXX_Size() int {
	return xxx_messageInfo_RespLogin.Size(m)
}
func (m *RespLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RespLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RespLogin proto.InternalMessageInfo

func (m *RespLogin) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

// SERVER PUSH : MSG_ID 300  // 推送房间类型列表
// 1.房间分类信息推送
type PushRoomClassify struct {
	RoomClassify         []*RoomClassify `protobuf:"bytes,1,rep,name=roomClassify,proto3" json:"roomClassify,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PushRoomClassify) Reset()         { *m = PushRoomClassify{} }
func (m *PushRoomClassify) String() string { return proto.CompactTextString(m) }
func (*PushRoomClassify) ProtoMessage()    {}
func (*PushRoomClassify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{2}
}

func (m *PushRoomClassify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRoomClassify.Unmarshal(m, b)
}
func (m *PushRoomClassify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRoomClassify.Marshal(b, m, deterministic)
}
func (m *PushRoomClassify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRoomClassify.Merge(m, src)
}
func (m *PushRoomClassify) XXX_Size() int {
	return xxx_messageInfo_PushRoomClassify.Size(m)
}
func (m *PushRoomClassify) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRoomClassify.DiscardUnknown(m)
}

var xxx_messageInfo_PushRoomClassify proto.InternalMessageInfo

func (m *PushRoomClassify) GetRoomClassify() []*RoomClassify {
	if m != nil {
		return m.RoomClassify
	}
	return nil
}

// SERVER PUSH : MSG_ID 301  // 推送房间玩家信息
// 1.推送房间玩家信息
type PushRoomPlayer struct {
	Players              []*RoomPlayer `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PushRoomPlayer) Reset()         { *m = PushRoomPlayer{} }
func (m *PushRoomPlayer) String() string { return proto.CompactTextString(m) }
func (*PushRoomPlayer) ProtoMessage()    {}
func (*PushRoomPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{3}
}

func (m *PushRoomPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRoomPlayer.Unmarshal(m, b)
}
func (m *PushRoomPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRoomPlayer.Marshal(b, m, deterministic)
}
func (m *PushRoomPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRoomPlayer.Merge(m, src)
}
func (m *PushRoomPlayer) XXX_Size() int {
	return xxx_messageInfo_PushRoomPlayer.Size(m)
}
func (m *PushRoomPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRoomPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_PushRoomPlayer proto.InternalMessageInfo

func (m *PushRoomPlayer) GetPlayers() []*RoomPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

// SERVER PUSH : MSG_ID 302  // 发牌
// 2.发牌
type PushStartGame struct {
	Cards                []*Card  `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushStartGame) Reset()         { *m = PushStartGame{} }
func (m *PushStartGame) String() string { return proto.CompactTextString(m) }
func (*PushStartGame) ProtoMessage()    {}
func (*PushStartGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{4}
}

func (m *PushStartGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushStartGame.Unmarshal(m, b)
}
func (m *PushStartGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushStartGame.Marshal(b, m, deterministic)
}
func (m *PushStartGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushStartGame.Merge(m, src)
}
func (m *PushStartGame) XXX_Size() int {
	return xxx_messageInfo_PushStartGame.Size(m)
}
func (m *PushStartGame) XXX_DiscardUnknown() {
	xxx_messageInfo_PushStartGame.DiscardUnknown(m)
}

var xxx_messageInfo_PushStartGame proto.InternalMessageInfo

func (m *PushStartGame) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

// SERVER PUSH : MSG_ID 303  // 抢地主阶段
// 3.抢地主阶段
type PushGetLandlord struct {
	LastPlayerId         string   `protobuf:"bytes,1,opt,name=lastPlayerId,proto3" json:"lastPlayerId,omitempty"`
	LastPlayerPosition   int32    `protobuf:"varint,2,opt,name=lastPlayerPosition,proto3" json:"lastPlayerPosition,omitempty"`
	LastPlayerAction     int32    `protobuf:"varint,3,opt,name=lastPlayerAction,proto3" json:"lastPlayerAction,omitempty"`
	PlayerId             string   `protobuf:"bytes,4,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerPosition       int32    `protobuf:"varint,5,opt,name=playerPosition,proto3" json:"playerPosition,omitempty"`
	Action               int32    `protobuf:"varint,6,opt,name=action,proto3" json:"action,omitempty"`
	Multi                int32    `protobuf:"varint,7,opt,name=multi,proto3" json:"multi,omitempty"`
	Countdown            int32    `protobuf:"varint,8,opt,name=Countdown,proto3" json:"Countdown,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushGetLandlord) Reset()         { *m = PushGetLandlord{} }
func (m *PushGetLandlord) String() string { return proto.CompactTextString(m) }
func (*PushGetLandlord) ProtoMessage()    {}
func (*PushGetLandlord) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{5}
}

func (m *PushGetLandlord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushGetLandlord.Unmarshal(m, b)
}
func (m *PushGetLandlord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushGetLandlord.Marshal(b, m, deterministic)
}
func (m *PushGetLandlord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushGetLandlord.Merge(m, src)
}
func (m *PushGetLandlord) XXX_Size() int {
	return xxx_messageInfo_PushGetLandlord.Size(m)
}
func (m *PushGetLandlord) XXX_DiscardUnknown() {
	xxx_messageInfo_PushGetLandlord.DiscardUnknown(m)
}

var xxx_messageInfo_PushGetLandlord proto.InternalMessageInfo

func (m *PushGetLandlord) GetLastPlayerId() string {
	if m != nil {
		return m.LastPlayerId
	}
	return ""
}

func (m *PushGetLandlord) GetLastPlayerPosition() int32 {
	if m != nil {
		return m.LastPlayerPosition
	}
	return 0
}

func (m *PushGetLandlord) GetLastPlayerAction() int32 {
	if m != nil {
		return m.LastPlayerAction
	}
	return 0
}

func (m *PushGetLandlord) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PushGetLandlord) GetPlayerPosition() int32 {
	if m != nil {
		return m.PlayerPosition
	}
	return 0
}

func (m *PushGetLandlord) GetAction() int32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *PushGetLandlord) GetMulti() int32 {
	if m != nil {
		return m.Multi
	}
	return 0
}

func (m *PushGetLandlord) GetCountdown() int32 {
	if m != nil {
		return m.Countdown
	}
	return 0
}

// SERVER PUSH : MSG_ID 304  // 地主推送
// 4.地主推送
type PushLandlord struct {
	LandlordId           string   `protobuf:"bytes,1,opt,name=landlordId,proto3" json:"landlordId,omitempty"`
	Position             int32    `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Cards                []*Card  `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushLandlord) Reset()         { *m = PushLandlord{} }
func (m *PushLandlord) String() string { return proto.CompactTextString(m) }
func (*PushLandlord) ProtoMessage()    {}
func (*PushLandlord) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{6}
}

func (m *PushLandlord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushLandlord.Unmarshal(m, b)
}
func (m *PushLandlord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushLandlord.Marshal(b, m, deterministic)
}
func (m *PushLandlord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushLandlord.Merge(m, src)
}
func (m *PushLandlord) XXX_Size() int {
	return xxx_messageInfo_PushLandlord.Size(m)
}
func (m *PushLandlord) XXX_DiscardUnknown() {
	xxx_messageInfo_PushLandlord.DiscardUnknown(m)
}

var xxx_messageInfo_PushLandlord proto.InternalMessageInfo

func (m *PushLandlord) GetLandlordId() string {
	if m != nil {
		return m.LandlordId
	}
	return ""
}

func (m *PushLandlord) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *PushLandlord) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

// SERVER PUSH : MSG_ID 305  // 出牌阶段
// 5.出牌阶段
type PushOutCard struct {
	LastPlayerId         string   `protobuf:"bytes,1,opt,name=lastPlayerId,proto3" json:"lastPlayerId,omitempty"`
	LastPlayerPosition   int32    `protobuf:"varint,2,opt,name=lastPlayerPosition,proto3" json:"lastPlayerPosition,omitempty"`
	LastPlayerCards      []*Card  `protobuf:"bytes,3,rep,name=lastPlayerCards,proto3" json:"lastPlayerCards,omitempty"`
	LastPlayerCardsType  int32    `protobuf:"varint,4,opt,name=lastPlayerCardsType,proto3" json:"lastPlayerCardsType,omitempty"`
	LastAction           int32    `protobuf:"varint,5,opt,name=lastAction,proto3" json:"lastAction,omitempty"`
	LastRemainLen        int32    `protobuf:"varint,6,opt,name=lastRemainLen,proto3" json:"lastRemainLen,omitempty"`
	PlayerId             string   `protobuf:"bytes,7,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerPosition       int32    `protobuf:"varint,8,opt,name=playerPosition,proto3" json:"playerPosition,omitempty"`
	IsMustPlay           bool     `protobuf:"varint,9,opt,name=isMustPlay,proto3" json:"isMustPlay,omitempty"`
	Multi                int32    `protobuf:"varint,10,opt,name=Multi,proto3" json:"Multi,omitempty"`
	Countdown            int32    `protobuf:"varint,11,opt,name=Countdown,proto3" json:"Countdown,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushOutCard) Reset()         { *m = PushOutCard{} }
func (m *PushOutCard) String() string { return proto.CompactTextString(m) }
func (*PushOutCard) ProtoMessage()    {}
func (*PushOutCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{7}
}

func (m *PushOutCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushOutCard.Unmarshal(m, b)
}
func (m *PushOutCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushOutCard.Marshal(b, m, deterministic)
}
func (m *PushOutCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushOutCard.Merge(m, src)
}
func (m *PushOutCard) XXX_Size() int {
	return xxx_messageInfo_PushOutCard.Size(m)
}
func (m *PushOutCard) XXX_DiscardUnknown() {
	xxx_messageInfo_PushOutCard.DiscardUnknown(m)
}

var xxx_messageInfo_PushOutCard proto.InternalMessageInfo

func (m *PushOutCard) GetLastPlayerId() string {
	if m != nil {
		return m.LastPlayerId
	}
	return ""
}

func (m *PushOutCard) GetLastPlayerPosition() int32 {
	if m != nil {
		return m.LastPlayerPosition
	}
	return 0
}

func (m *PushOutCard) GetLastPlayerCards() []*Card {
	if m != nil {
		return m.LastPlayerCards
	}
	return nil
}

func (m *PushOutCard) GetLastPlayerCardsType() int32 {
	if m != nil {
		return m.LastPlayerCardsType
	}
	return 0
}

func (m *PushOutCard) GetLastAction() int32 {
	if m != nil {
		return m.LastAction
	}
	return 0
}

func (m *PushOutCard) GetLastRemainLen() int32 {
	if m != nil {
		return m.LastRemainLen
	}
	return 0
}

func (m *PushOutCard) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PushOutCard) GetPlayerPosition() int32 {
	if m != nil {
		return m.PlayerPosition
	}
	return 0
}

func (m *PushOutCard) GetIsMustPlay() bool {
	if m != nil {
		return m.IsMustPlay
	}
	return false
}

func (m *PushOutCard) GetMulti() int32 {
	if m != nil {
		return m.Multi
	}
	return 0
}

func (m *PushOutCard) GetCountdown() int32 {
	if m != nil {
		return m.Countdown
	}
	return 0
}

// SERVER PUSH : MSG_ID 306  // 出牌阶段
// 6.出牌阶段
type PushSettlement struct {
	Settlement           []*Settlement `protobuf:"bytes,1,rep,name=settlement,proto3" json:"settlement,omitempty"`
	MultipleInfo         *MultipleInfo `protobuf:"bytes,2,opt,name=MultipleInfo,proto3" json:"MultipleInfo,omitempty"`
	WaitTime             int32         `protobuf:"varint,3,opt,name=waitTime,proto3" json:"waitTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PushSettlement) Reset()         { *m = PushSettlement{} }
func (m *PushSettlement) String() string { return proto.CompactTextString(m) }
func (*PushSettlement) ProtoMessage()    {}
func (*PushSettlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{8}
}

func (m *PushSettlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushSettlement.Unmarshal(m, b)
}
func (m *PushSettlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushSettlement.Marshal(b, m, deterministic)
}
func (m *PushSettlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushSettlement.Merge(m, src)
}
func (m *PushSettlement) XXX_Size() int {
	return xxx_messageInfo_PushSettlement.Size(m)
}
func (m *PushSettlement) XXX_DiscardUnknown() {
	xxx_messageInfo_PushSettlement.DiscardUnknown(m)
}

var xxx_messageInfo_PushSettlement proto.InternalMessageInfo

func (m *PushSettlement) GetSettlement() []*Settlement {
	if m != nil {
		return m.Settlement
	}
	return nil
}

func (m *PushSettlement) GetMultipleInfo() *MultipleInfo {
	if m != nil {
		return m.MultipleInfo
	}
	return nil
}

func (m *PushSettlement) GetWaitTime() int32 {
	if m != nil {
		return m.WaitTime
	}
	return 0
}

// SERVER PUSH : MSG_ID 307  // 房间恢复
// MSG_ROOM_INFO_PUSH = 307 ;
// 7.玩家在玩的过程中 退出房间  在进入 的房间数据信息推送
type PushRoomRecover struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRoomRecover) Reset()         { *m = PushRoomRecover{} }
func (m *PushRoomRecover) String() string { return proto.CompactTextString(m) }
func (*PushRoomRecover) ProtoMessage()    {}
func (*PushRoomRecover) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{9}
}

func (m *PushRoomRecover) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRoomRecover.Unmarshal(m, b)
}
func (m *PushRoomRecover) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRoomRecover.Marshal(b, m, deterministic)
}
func (m *PushRoomRecover) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRoomRecover.Merge(m, src)
}
func (m *PushRoomRecover) XXX_Size() int {
	return xxx_messageInfo_PushRoomRecover.Size(m)
}
func (m *PushRoomRecover) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRoomRecover.DiscardUnknown(m)
}

var xxx_messageInfo_PushRoomRecover proto.InternalMessageInfo

// SERVER PUSH : MSG_ID 500  // 服务器断开指令
// 1.断开连接指令
type CloseConn struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseConn) Reset()         { *m = CloseConn{} }
func (m *CloseConn) String() string { return proto.CompactTextString(m) }
func (*CloseConn) ProtoMessage()    {}
func (*CloseConn) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{10}
}

func (m *CloseConn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseConn.Unmarshal(m, b)
}
func (m *CloseConn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseConn.Marshal(b, m, deterministic)
}
func (m *CloseConn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseConn.Merge(m, src)
}
func (m *CloseConn) XXX_Size() int {
	return xxx_messageInfo_CloseConn.Size(m)
}
func (m *CloseConn) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseConn.DiscardUnknown(m)
}

var xxx_messageInfo_CloseConn proto.InternalMessageInfo

func (m *CloseConn) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CloseConn) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// SERVER PUSH : MSG_ID 501  // 服务器错误指令
// 1.服务器错误指令
type ErrMsg struct {
	MsgId                int32    `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrMsg) Reset()         { *m = ErrMsg{} }
func (m *ErrMsg) String() string { return proto.CompactTextString(m) }
func (*ErrMsg) ProtoMessage()    {}
func (*ErrMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{11}
}

func (m *ErrMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrMsg.Unmarshal(m, b)
}
func (m *ErrMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrMsg.Marshal(b, m, deterministic)
}
func (m *ErrMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrMsg.Merge(m, src)
}
func (m *ErrMsg) XXX_Size() int {
	return xxx_messageInfo_ErrMsg.Size(m)
}
func (m *ErrMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ErrMsg proto.InternalMessageInfo

func (m *ErrMsg) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *ErrMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// ============================================= 属性data =================================
// 1.PushStartGame
type RoomPlayer struct {
	Players              *PlayerInfo `protobuf:"bytes,1,opt,name=players,proto3" json:"players,omitempty"`
	Position             int32       `protobuf:"varint,2,opt,name=Position,proto3" json:"Position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RoomPlayer) Reset()         { *m = RoomPlayer{} }
func (m *RoomPlayer) String() string { return proto.CompactTextString(m) }
func (*RoomPlayer) ProtoMessage()    {}
func (*RoomPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{12}
}

func (m *RoomPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomPlayer.Unmarshal(m, b)
}
func (m *RoomPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomPlayer.Marshal(b, m, deterministic)
}
func (m *RoomPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomPlayer.Merge(m, src)
}
func (m *RoomPlayer) XXX_Size() int {
	return xxx_messageInfo_RoomPlayer.Size(m)
}
func (m *RoomPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_RoomPlayer proto.InternalMessageInfo

func (m *RoomPlayer) GetPlayers() *PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *RoomPlayer) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

// 1. LoginResp   2.PlayerListPush
type PlayerInfo struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`
	PlayerImg            string   `protobuf:"bytes,3,opt,name=playerImg,proto3" json:"playerImg,omitempty"`
	Gold                 float64  `protobuf:"fixed64,4,opt,name=gold,proto3" json:"gold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{13}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PlayerInfo) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *PlayerInfo) GetPlayerImg() string {
	if m != nil {
		return m.PlayerImg
	}
	return ""
}

func (m *PlayerInfo) GetGold() float64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

// RoomClassifyPush
type RoomClassify struct {
	RoomType             int32    `protobuf:"varint,1,opt,name=roomType,proto3" json:"roomType,omitempty"`
	BottomPoint          float64  `protobuf:"fixed64,2,opt,name=bottomPoint,proto3" json:"bottomPoint,omitempty"`
	BottomEnterPoint     float64  `protobuf:"fixed64,3,opt,name=bottomEnterPoint,proto3" json:"bottomEnterPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomClassify) Reset()         { *m = RoomClassify{} }
func (m *RoomClassify) String() string { return proto.CompactTextString(m) }
func (*RoomClassify) ProtoMessage()    {}
func (*RoomClassify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{14}
}

func (m *RoomClassify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomClassify.Unmarshal(m, b)
}
func (m *RoomClassify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomClassify.Marshal(b, m, deterministic)
}
func (m *RoomClassify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomClassify.Merge(m, src)
}
func (m *RoomClassify) XXX_Size() int {
	return xxx_messageInfo_RoomClassify.Size(m)
}
func (m *RoomClassify) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomClassify.DiscardUnknown(m)
}

var xxx_messageInfo_RoomClassify proto.InternalMessageInfo

func (m *RoomClassify) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *RoomClassify) GetBottomPoint() float64 {
	if m != nil {
		return m.BottomPoint
	}
	return 0
}

func (m *RoomClassify) GetBottomEnterPoint() float64 {
	if m != nil {
		return m.BottomEnterPoint
	}
	return 0
}

// PushStartGame
type Card struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Suit                 int32    `protobuf:"varint,2,opt,name=suit,proto3" json:"suit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{15}
}

func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Card) GetSuit() int32 {
	if m != nil {
		return m.Suit
	}
	return 0
}

// 结算详细信息
type Settlement struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`
	IsLandlord           int32    `protobuf:"varint,3,opt,name=isLandlord,proto3" json:"isLandlord,omitempty"`
	Multiple             int32    `protobuf:"varint,4,opt,name=multiple,proto3" json:"multiple,omitempty"`
	WinLossGold          string   `protobuf:"bytes,5,opt,name=winLossGold,proto3" json:"winLossGold,omitempty"`
	CurrentGold          float64  `protobuf:"fixed64,6,opt,name=currentGold,proto3" json:"currentGold,omitempty"`
	WinOrFail            int32    `protobuf:"varint,7,opt,name=winOrFail,proto3" json:"winOrFail,omitempty"`
	MinSettlement        bool     `protobuf:"varint,8,opt,name=minSettlement,proto3" json:"minSettlement,omitempty"`
	RemainCards          []*Card  `protobuf:"bytes,9,rep,name=remainCards,proto3" json:"remainCards,omitempty"`
	Position             int32    `protobuf:"varint,10,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Settlement) Reset()         { *m = Settlement{} }
func (m *Settlement) String() string { return proto.CompactTextString(m) }
func (*Settlement) ProtoMessage()    {}
func (*Settlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{16}
}

func (m *Settlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Settlement.Unmarshal(m, b)
}
func (m *Settlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Settlement.Marshal(b, m, deterministic)
}
func (m *Settlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Settlement.Merge(m, src)
}
func (m *Settlement) XXX_Size() int {
	return xxx_messageInfo_Settlement.Size(m)
}
func (m *Settlement) XXX_DiscardUnknown() {
	xxx_messageInfo_Settlement.DiscardUnknown(m)
}

var xxx_messageInfo_Settlement proto.InternalMessageInfo

func (m *Settlement) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *Settlement) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *Settlement) GetIsLandlord() int32 {
	if m != nil {
		return m.IsLandlord
	}
	return 0
}

func (m *Settlement) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

func (m *Settlement) GetWinLossGold() string {
	if m != nil {
		return m.WinLossGold
	}
	return ""
}

func (m *Settlement) GetCurrentGold() float64 {
	if m != nil {
		return m.CurrentGold
	}
	return 0
}

func (m *Settlement) GetWinOrFail() int32 {
	if m != nil {
		return m.WinOrFail
	}
	return 0
}

func (m *Settlement) GetMinSettlement() bool {
	if m != nil {
		return m.MinSettlement
	}
	return false
}

func (m *Settlement) GetRemainCards() []*Card {
	if m != nil {
		return m.RemainCards
	}
	return nil
}

func (m *Settlement) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

// 倍数详细信息
type MultipleInfo struct {
	// 前端每轮显示 *3 的房间底分倍数
	FightLandlord        string   `protobuf:"bytes,2,opt,name=fightLandlord,proto3" json:"fightLandlord,omitempty"`
	Boom                 string   `protobuf:"bytes,3,opt,name=boom,proto3" json:"boom,omitempty"`
	Spring               string   `protobuf:"bytes,1,opt,name=spring,proto3" json:"spring,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultipleInfo) Reset()         { *m = MultipleInfo{} }
func (m *MultipleInfo) String() string { return proto.CompactTextString(m) }
func (*MultipleInfo) ProtoMessage()    {}
func (*MultipleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{17}
}

func (m *MultipleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleInfo.Unmarshal(m, b)
}
func (m *MultipleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleInfo.Marshal(b, m, deterministic)
}
func (m *MultipleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleInfo.Merge(m, src)
}
func (m *MultipleInfo) XXX_Size() int {
	return xxx_messageInfo_MultipleInfo.Size(m)
}
func (m *MultipleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleInfo proto.InternalMessageInfo

func (m *MultipleInfo) GetFightLandlord() string {
	if m != nil {
		return m.FightLandlord
	}
	return ""
}

func (m *MultipleInfo) GetBoom() string {
	if m != nil {
		return m.Boom
	}
	return ""
}

func (m *MultipleInfo) GetSpring() string {
	if m != nil {
		return m.Spring
	}
	return ""
}

func init() {
	proto.RegisterType((*PONG)(nil), "mproto.PONG")
	proto.RegisterType((*RespLogin)(nil), "mproto.RespLogin")
	proto.RegisterType((*PushRoomClassify)(nil), "mproto.PushRoomClassify")
	proto.RegisterType((*PushRoomPlayer)(nil), "mproto.PushRoomPlayer")
	proto.RegisterType((*PushStartGame)(nil), "mproto.PushStartGame")
	proto.RegisterType((*PushGetLandlord)(nil), "mproto.PushGetLandlord")
	proto.RegisterType((*PushLandlord)(nil), "mproto.PushLandlord")
	proto.RegisterType((*PushOutCard)(nil), "mproto.PushOutCard")
	proto.RegisterType((*PushSettlement)(nil), "mproto.PushSettlement")
	proto.RegisterType((*PushRoomRecover)(nil), "mproto.PushRoomRecover")
	proto.RegisterType((*CloseConn)(nil), "mproto.CloseConn")
	proto.RegisterType((*ErrMsg)(nil), "mproto.ErrMsg")
	proto.RegisterType((*RoomPlayer)(nil), "mproto.RoomPlayer")
	proto.RegisterType((*PlayerInfo)(nil), "mproto.PlayerInfo")
	proto.RegisterType((*RoomClassify)(nil), "mproto.RoomClassify")
	proto.RegisterType((*Card)(nil), "mproto.Card")
	proto.RegisterType((*Settlement)(nil), "mproto.Settlement")
	proto.RegisterType((*MultipleInfo)(nil), "mproto.MultipleInfo")
}

func init() { proto.RegisterFile("resp.proto", fileDescriptor_3c5365792f61ddff) }

var fileDescriptor_3c5365792f61ddff = []byte{
	// 846 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x51, 0x6b, 0x23, 0x37,
	0x10, 0x66, 0xed, 0xd8, 0xb1, 0xc7, 0xbe, 0xbb, 0x54, 0x0d, 0xc5, 0x84, 0x12, 0x8c, 0x28, 0x25,
	0x94, 0x62, 0xd2, 0x1c, 0x94, 0x3e, 0xb5, 0x14, 0x73, 0x0d, 0x05, 0xe7, 0x62, 0x74, 0x47, 0x9f,
	0xbb, 0xb1, 0x15, 0x9f, 0x60, 0x57, 0x5a, 0x56, 0xda, 0x4b, 0xd3, 0x9f, 0xd2, 0xb7, 0x3e, 0xf6,
	0x1f, 0xf5, 0xe7, 0x94, 0x19, 0x69, 0x77, 0xb5, 0x8e, 0x43, 0x1f, 0x4a, 0x9f, 0xac, 0xf9, 0xf4,
	0x49, 0xa3, 0x9d, 0xf9, 0xe6, 0x33, 0x40, 0x29, 0x6d, 0xb1, 0x28, 0x4a, 0xe3, 0x0c, 0x1b, 0xe6,
	0xf4, 0xcb, 0xcf, 0xe0, 0x68, 0x7d, 0xfb, 0xf6, 0x9a, 0x31, 0x38, 0x72, 0x2a, 0x97, 0xb3, 0x64,
	0x9e, 0x5c, 0xf4, 0x05, 0xad, 0xf9, 0x0f, 0x30, 0x16, 0xd2, 0x16, 0x2b, 0xb3, 0x53, 0x9a, 0x5d,
	0x01, 0x14, 0x59, 0xfa, 0x28, 0xcb, 0x9f, 0xf5, 0xbd, 0x21, 0xda, 0xe4, 0x8a, 0x2d, 0xfc, 0x2d,
	0x8b, 0x75, 0xb3, 0x23, 0x22, 0x16, 0x5f, 0xc1, 0xc9, 0xba, 0xb2, 0x1f, 0x84, 0x31, 0xf9, 0x32,
	0x4b, 0xad, 0x55, 0xf7, 0x8f, 0xec, 0x3b, 0x98, 0x96, 0x51, 0x3c, 0x4b, 0xe6, 0xfd, 0x8b, 0xc9,
	0xd5, 0x69, 0x7d, 0x53, 0xcc, 0x15, 0x1d, 0x26, 0xff, 0x1e, 0x5e, 0xd6, 0xb7, 0xf9, 0x7c, 0xec,
	0x6b, 0x38, 0xf6, 0xd9, 0x6c, 0xb8, 0x86, 0xc5, 0xd7, 0x78, 0x92, 0xa8, 0x29, 0xfc, 0x35, 0xbc,
	0xc0, 0xf3, 0xef, 0x5c, 0x5a, 0xba, 0xeb, 0x34, 0x97, 0x8c, 0xc3, 0x60, 0x93, 0x96, 0x5b, 0x3b,
	0xeb, 0xd1, 0xe1, 0x69, 0x7d, 0x78, 0x99, 0x96, 0x5b, 0xe1, 0xb7, 0xf8, 0x9f, 0x3d, 0x78, 0x85,
	0xa7, 0xae, 0xa5, 0x5b, 0xa5, 0x7a, 0x9b, 0x99, 0x72, 0xcb, 0x38, 0x4c, 0xb3, 0xd4, 0xba, 0xf0,
	0xd1, 0x5b, 0x2a, 0xc6, 0x58, 0x74, 0x30, 0xb6, 0x00, 0xd6, 0xc6, 0x6b, 0x63, 0x95, 0x53, 0x46,
	0xcf, 0x7a, 0xf3, 0xe4, 0x62, 0x20, 0x0e, 0xec, 0xb0, 0xaf, 0xe0, 0xa4, 0x45, 0x7f, 0xdc, 0x10,
	0xbb, 0x4f, 0xec, 0x27, 0x38, 0x3b, 0x83, 0x51, 0x51, 0xe7, 0x3e, 0xa2, 0xdc, 0x4d, 0xcc, 0xbe,
	0x84, 0x97, 0x45, 0x37, 0xe7, 0x80, 0x6e, 0xd9, 0x43, 0xd9, 0x67, 0x30, 0x4c, 0x7d, 0x96, 0x21,
	0xed, 0x87, 0x88, 0x9d, 0xc2, 0x20, 0xaf, 0x32, 0xa7, 0x66, 0xc7, 0x04, 0xfb, 0x80, 0x7d, 0x0e,
	0xe3, 0xa5, 0xa9, 0xb4, 0xdb, 0x9a, 0x07, 0x3d, 0x1b, 0xd1, 0x4e, 0x0b, 0x70, 0x0d, 0x53, 0x2c,
	0x51, 0x53, 0x9f, 0x73, 0x80, 0x2c, 0xac, 0x9b, 0xea, 0x44, 0x08, 0xbd, 0xbf, 0x5b, 0x91, 0x26,
	0x6e, 0x7b, 0xd2, 0x7f, 0xbe, 0x27, 0x7f, 0xf5, 0x61, 0x82, 0x09, 0x6f, 0x2b, 0x87, 0xf0, 0xff,
	0xd2, 0x8f, 0x6f, 0xe1, 0x55, 0x8b, 0x2e, 0x9f, 0x7d, 0xd1, 0x3e, 0x89, 0x5d, 0xc2, 0xa7, 0x7b,
	0xd0, 0xfb, 0xc7, 0x42, 0x52, 0x9b, 0x06, 0xe2, 0xd0, 0x96, 0xaf, 0x96, 0x75, 0xa1, 0xe7, 0xbe,
	0x5b, 0x11, 0xc2, 0xbe, 0x80, 0x17, 0x18, 0x09, 0x99, 0xa7, 0x4a, 0xaf, 0x64, 0xdd, 0xb0, 0x2e,
	0xd8, 0xd1, 0xc4, 0xf1, 0xbf, 0x6a, 0x62, 0x74, 0x50, 0x13, 0xe7, 0x00, 0xca, 0xde, 0x54, 0xfe,
	0x89, 0xb3, 0xf1, 0x3c, 0xb9, 0x18, 0x89, 0x08, 0x41, 0x6d, 0xdc, 0x90, 0x36, 0xc0, 0x6b, 0xe3,
	0xe6, 0xa9, 0x36, 0x26, 0xfb, 0xda, 0xf8, 0x23, 0xf1, 0x53, 0xfb, 0x4e, 0x3a, 0x97, 0xc9, 0x5c,
	0x6a, 0x87, 0x4e, 0x62, 0x9b, 0x68, 0x7f, 0x70, 0x5b, 0x9e, 0x88, 0x58, 0xe8, 0x1a, 0x94, 0xad,
	0xc8, 0x24, 0xf9, 0x4f, 0x8f, 0xfc, 0xa7, 0x71, 0x8d, 0x78, 0x4f, 0x74, 0x98, 0x58, 0x98, 0x87,
	0x54, 0xb9, 0xf7, 0x68, 0x6e, 0x7e, 0xa0, 0x9a, 0x98, 0x7f, 0xe2, 0x67, 0x1b, 0xcd, 0x42, 0xc8,
	0x8d, 0xf9, 0x28, 0x4b, 0xfe, 0x0d, 0x8c, 0x97, 0x99, 0xb1, 0x72, 0x69, 0xb4, 0x46, 0x53, 0xdc,
	0x98, 0xad, 0x37, 0xc5, 0x81, 0xa0, 0x35, 0x3b, 0x81, 0x7e, 0x6e, 0x77, 0xf4, 0x80, 0xb1, 0xc0,
	0x25, 0xbf, 0x84, 0xe1, 0x9b, 0xb2, 0xbc, 0xb1, 0x3b, 0x1a, 0x1e, 0xbb, 0x0b, 0x0a, 0xc4, 0xe1,
	0xc1, 0xe0, 0xc0, 0x89, 0x5f, 0x00, 0x9e, 0x73, 0xb1, 0xe7, 0x6c, 0xb5, 0xa6, 0xe0, 0xf7, 0xec,
	0xc9, 0xb7, 0x89, 0xf9, 0xef, 0x00, 0xed, 0x91, 0x8e, 0x24, 0x92, 0x3d, 0x49, 0x9c, 0xd7, 0x6e,
	0xfe, 0x36, 0xcd, 0x65, 0x78, 0x5a, 0x84, 0x60, 0x53, 0x03, 0x37, 0xdf, 0x51, 0xd9, 0xc6, 0xa2,
	0x05, 0xb0, 0x2e, 0x3b, 0x93, 0x79, 0xf3, 0x49, 0x04, 0xad, 0xf9, 0x6f, 0x30, 0xed, 0xf8, 0xfc,
	0x19, 0x8c, 0xd0, 0xbd, 0x49, 0xfd, 0xbe, 0x1c, 0x4d, 0xcc, 0xe6, 0x30, 0xb9, 0x33, 0xce, 0x99,
	0x7c, 0x6d, 0x94, 0x76, 0x94, 0x3e, 0x11, 0x31, 0x84, 0x76, 0xe8, 0xc3, 0x37, 0xda, 0xa1, 0x42,
	0x91, 0xd6, 0x27, 0xda, 0x13, 0x9c, 0x5f, 0xc2, 0x11, 0xd9, 0xc0, 0x29, 0x0c, 0x3e, 0xa6, 0x59,
	0x55, 0xa7, 0xf3, 0x01, 0xbe, 0xd5, 0x56, 0xca, 0x85, 0x5a, 0xd1, 0x9a, 0xff, 0xdd, 0x03, 0x88,
	0x04, 0xf9, 0x5f, 0x0a, 0x45, 0x33, 0x53, 0x3b, 0x5f, 0x10, 0x58, 0x84, 0xe0, 0xdd, 0x79, 0x90,
	0x63, 0x30, 0x81, 0x26, 0xc6, 0x32, 0x3c, 0x28, 0xbd, 0x32, 0xd6, 0x5e, 0x63, 0x35, 0x07, 0x74,
	0x79, 0x0c, 0x21, 0x63, 0x53, 0x95, 0xa5, 0xd4, 0x8e, 0x18, 0x43, 0x5f, 0xa8, 0x08, 0xc2, 0x46,
	0x3d, 0x28, 0x7d, 0x5b, 0xfe, 0x94, 0xaa, 0x2c, 0x78, 0x76, 0x0b, 0xa0, 0x77, 0xe4, 0x4a, 0xb7,
	0x9f, 0x4a, 0x83, 0x3f, 0x12, 0x5d, 0x90, 0x2d, 0x60, 0x52, 0x92, 0x91, 0x78, 0x9f, 0x1b, 0x1f,
	0xf0, 0xb9, 0x98, 0xd0, 0xf1, 0x6f, 0xe8, 0xfa, 0x37, 0xff, 0xb5, 0x3b, 0xa8, 0xf8, 0x82, 0x7b,
	0xb5, 0xfb, 0xd0, 0xfc, 0x79, 0x86, 0x12, 0x76, 0x41, 0x6c, 0xd2, 0x9d, 0x31, 0x79, 0x50, 0x1a,
	0xad, 0xf1, 0x1f, 0xca, 0x16, 0xa5, 0xd2, 0xbb, 0xd0, 0x93, 0x10, 0xdd, 0x0d, 0xe9, 0x59, 0xaf,
	0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x8f, 0x06, 0xd3, 0xce, 0x08, 0x00, 0x00,
}
