// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resp.proto

package mproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// =================================  SERVER 收到指令返回 200 pong 消息为1 开始 ===========
// SERVER RESP : MSG_ID 1
// 1.PONG
type PONG struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PONG) Reset()         { *m = PONG{} }
func (m *PONG) String() string { return proto.CompactTextString(m) }
func (*PONG) ProtoMessage()    {}
func (*PONG) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{0}
}

func (m *PONG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PONG.Unmarshal(m, b)
}
func (m *PONG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PONG.Marshal(b, m, deterministic)
}
func (m *PONG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PONG.Merge(m, src)
}
func (m *PONG) XXX_Size() int {
	return xxx_messageInfo_PONG.Size(m)
}
func (m *PONG) XXX_DiscardUnknown() {
	xxx_messageInfo_PONG.DiscardUnknown(m)
}

var xxx_messageInfo_PONG proto.InternalMessageInfo

func (m *PONG) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// SERVER RESP : MSG_ID 200
// 1.登录返回
type RespLogin struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RespLogin) Reset()         { *m = RespLogin{} }
func (m *RespLogin) String() string { return proto.CompactTextString(m) }
func (*RespLogin) ProtoMessage()    {}
func (*RespLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{1}
}

func (m *RespLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespLogin.Unmarshal(m, b)
}
func (m *RespLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespLogin.Marshal(b, m, deterministic)
}
func (m *RespLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespLogin.Merge(m, src)
}
func (m *RespLogin) XXX_Size() int {
	return xxx_messageInfo_RespLogin.Size(m)
}
func (m *RespLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RespLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RespLogin proto.InternalMessageInfo

func (m *RespLogin) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

// SERVER PUSH : MSG_ID 300  // 推送房间类型列表
// 1.房间分类信息推送
type PushRoomClassify struct {
	RoomClassify         []*RoomClassify `protobuf:"bytes,1,rep,name=roomClassify,proto3" json:"roomClassify,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PushRoomClassify) Reset()         { *m = PushRoomClassify{} }
func (m *PushRoomClassify) String() string { return proto.CompactTextString(m) }
func (*PushRoomClassify) ProtoMessage()    {}
func (*PushRoomClassify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{2}
}

func (m *PushRoomClassify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRoomClassify.Unmarshal(m, b)
}
func (m *PushRoomClassify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRoomClassify.Marshal(b, m, deterministic)
}
func (m *PushRoomClassify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRoomClassify.Merge(m, src)
}
func (m *PushRoomClassify) XXX_Size() int {
	return xxx_messageInfo_PushRoomClassify.Size(m)
}
func (m *PushRoomClassify) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRoomClassify.DiscardUnknown(m)
}

var xxx_messageInfo_PushRoomClassify proto.InternalMessageInfo

func (m *PushRoomClassify) GetRoomClassify() []*RoomClassify {
	if m != nil {
		return m.RoomClassify
	}
	return nil
}

// SERVER PUSH : MSG_ID 301  // 推送房间信息
// 2.对局房间信息推送
type PushPlayRoom struct {
	RoomClassify         *RoomClassify     `protobuf:"bytes,1,opt,name=roomClassify,proto3" json:"roomClassify,omitempty"`
	RoomPlayer           []*RoomPlayerInfo `protobuf:"bytes,2,rep,name=roomPlayer,proto3" json:"roomPlayer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PushPlayRoom) Reset()         { *m = PushPlayRoom{} }
func (m *PushPlayRoom) String() string { return proto.CompactTextString(m) }
func (*PushPlayRoom) ProtoMessage()    {}
func (*PushPlayRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{3}
}

func (m *PushPlayRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPlayRoom.Unmarshal(m, b)
}
func (m *PushPlayRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPlayRoom.Marshal(b, m, deterministic)
}
func (m *PushPlayRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPlayRoom.Merge(m, src)
}
func (m *PushPlayRoom) XXX_Size() int {
	return xxx_messageInfo_PushPlayRoom.Size(m)
}
func (m *PushPlayRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPlayRoom.DiscardUnknown(m)
}

var xxx_messageInfo_PushPlayRoom proto.InternalMessageInfo

func (m *PushPlayRoom) GetRoomClassify() *RoomClassify {
	if m != nil {
		return m.RoomClassify
	}
	return nil
}

func (m *PushPlayRoom) GetRoomPlayer() []*RoomPlayerInfo {
	if m != nil {
		return m.RoomPlayer
	}
	return nil
}

// SERVER PUSH : MSG_ID 302   // 推送骰子 点数 // 前端收到此消息 显示开局和掷骰子动画
// 2.开局投掷骰子信息推送
type PushDice struct {
	Dice1                int32    `protobuf:"varint,1,opt,name=dice1,proto3" json:"dice1,omitempty"`
	Dice2                int32    `protobuf:"varint,2,opt,name=dice2,proto3" json:"dice2,omitempty"`
	VillagePlayerId      string   `protobuf:"bytes,3,opt,name=villagePlayerId,proto3" json:"villagePlayerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushDice) Reset()         { *m = PushDice{} }
func (m *PushDice) String() string { return proto.CompactTextString(m) }
func (*PushDice) ProtoMessage()    {}
func (*PushDice) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{4}
}

func (m *PushDice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushDice.Unmarshal(m, b)
}
func (m *PushDice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushDice.Marshal(b, m, deterministic)
}
func (m *PushDice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushDice.Merge(m, src)
}
func (m *PushDice) XXX_Size() int {
	return xxx_messageInfo_PushDice.Size(m)
}
func (m *PushDice) XXX_DiscardUnknown() {
	xxx_messageInfo_PushDice.DiscardUnknown(m)
}

var xxx_messageInfo_PushDice proto.InternalMessageInfo

func (m *PushDice) GetDice1() int32 {
	if m != nil {
		return m.Dice1
	}
	return 0
}

func (m *PushDice) GetDice2() int32 {
	if m != nil {
		return m.Dice2
	}
	return 0
}

func (m *PushDice) GetVillagePlayerId() string {
	if m != nil {
		return m.VillagePlayerId
	}
	return ""
}

// SERVER PUSH : MSG_ID 303
// 3.发牌信息推送
type PushLicensing struct {
	HandleMahjong        []int32  `protobuf:"varint,1,rep,packed,name=handleMahjong,proto3" json:"handleMahjong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushLicensing) Reset()         { *m = PushLicensing{} }
func (m *PushLicensing) String() string { return proto.CompactTextString(m) }
func (*PushLicensing) ProtoMessage()    {}
func (*PushLicensing) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{5}
}

func (m *PushLicensing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushLicensing.Unmarshal(m, b)
}
func (m *PushLicensing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushLicensing.Marshal(b, m, deterministic)
}
func (m *PushLicensing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushLicensing.Merge(m, src)
}
func (m *PushLicensing) XXX_Size() int {
	return xxx_messageInfo_PushLicensing.Size(m)
}
func (m *PushLicensing) XXX_DiscardUnknown() {
	xxx_messageInfo_PushLicensing.DiscardUnknown(m)
}

var xxx_messageInfo_PushLicensing proto.InternalMessageInfo

func (m *PushLicensing) GetHandleMahjong() []int32 {
	if m != nil {
		return m.HandleMahjong
	}
	return nil
}

// SERVER PUSH : MSG_ID 304
// 4.玩家牌改变推送
type PushPlayerChangesMahjongs struct {
	ChangesMahjongs      *PlayerChangesMahjongs `protobuf:"bytes,1,opt,name=changesMahjongs,proto3" json:"changesMahjongs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PushPlayerChangesMahjongs) Reset()         { *m = PushPlayerChangesMahjongs{} }
func (m *PushPlayerChangesMahjongs) String() string { return proto.CompactTextString(m) }
func (*PushPlayerChangesMahjongs) ProtoMessage()    {}
func (*PushPlayerChangesMahjongs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{6}
}

func (m *PushPlayerChangesMahjongs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPlayerChangesMahjongs.Unmarshal(m, b)
}
func (m *PushPlayerChangesMahjongs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPlayerChangesMahjongs.Marshal(b, m, deterministic)
}
func (m *PushPlayerChangesMahjongs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPlayerChangesMahjongs.Merge(m, src)
}
func (m *PushPlayerChangesMahjongs) XXX_Size() int {
	return xxx_messageInfo_PushPlayerChangesMahjongs.Size(m)
}
func (m *PushPlayerChangesMahjongs) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPlayerChangesMahjongs.DiscardUnknown(m)
}

var xxx_messageInfo_PushPlayerChangesMahjongs proto.InternalMessageInfo

func (m *PushPlayerChangesMahjongs) GetChangesMahjongs() *PlayerChangesMahjongs {
	if m != nil {
		return m.ChangesMahjongs
	}
	return nil
}

// SERVER PUSH : MSG_ID 305
// 5.对方玩家牌改变推送
type PushOtherPlayerChangesMahjongs struct {
	ChangesMahjongs      *OtherPlayerChangesMahjongs `protobuf:"bytes,1,opt,name=changesMahjongs,proto3" json:"changesMahjongs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PushOtherPlayerChangesMahjongs) Reset()         { *m = PushOtherPlayerChangesMahjongs{} }
func (m *PushOtherPlayerChangesMahjongs) String() string { return proto.CompactTextString(m) }
func (*PushOtherPlayerChangesMahjongs) ProtoMessage()    {}
func (*PushOtherPlayerChangesMahjongs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{7}
}

func (m *PushOtherPlayerChangesMahjongs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushOtherPlayerChangesMahjongs.Unmarshal(m, b)
}
func (m *PushOtherPlayerChangesMahjongs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushOtherPlayerChangesMahjongs.Marshal(b, m, deterministic)
}
func (m *PushOtherPlayerChangesMahjongs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushOtherPlayerChangesMahjongs.Merge(m, src)
}
func (m *PushOtherPlayerChangesMahjongs) XXX_Size() int {
	return xxx_messageInfo_PushOtherPlayerChangesMahjongs.Size(m)
}
func (m *PushOtherPlayerChangesMahjongs) XXX_DiscardUnknown() {
	xxx_messageInfo_PushOtherPlayerChangesMahjongs.DiscardUnknown(m)
}

var xxx_messageInfo_PushOtherPlayerChangesMahjongs proto.InternalMessageInfo

func (m *PushOtherPlayerChangesMahjongs) GetChangesMahjongs() *OtherPlayerChangesMahjongs {
	if m != nil {
		return m.ChangesMahjongs
	}
	return nil
}

// SERVER PUSH : MSG_ID 306
// 6. 推送 玩家摸牌
type PushGetOneMahjong struct {
	TableRemainingMahjongsLen int32    `protobuf:"varint,1,opt,name=tableRemainingMahjongsLen,proto3" json:"tableRemainingMahjongsLen,omitempty"`
	IsSelf                    bool     `protobuf:"varint,2,opt,name=isSelf,proto3" json:"isSelf,omitempty"`
	Mahjong                   int32    `protobuf:"varint,3,opt,name=mahjong,proto3" json:"mahjong,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *PushGetOneMahjong) Reset()         { *m = PushGetOneMahjong{} }
func (m *PushGetOneMahjong) String() string { return proto.CompactTextString(m) }
func (*PushGetOneMahjong) ProtoMessage()    {}
func (*PushGetOneMahjong) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{8}
}

func (m *PushGetOneMahjong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushGetOneMahjong.Unmarshal(m, b)
}
func (m *PushGetOneMahjong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushGetOneMahjong.Marshal(b, m, deterministic)
}
func (m *PushGetOneMahjong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushGetOneMahjong.Merge(m, src)
}
func (m *PushGetOneMahjong) XXX_Size() int {
	return xxx_messageInfo_PushGetOneMahjong.Size(m)
}
func (m *PushGetOneMahjong) XXX_DiscardUnknown() {
	xxx_messageInfo_PushGetOneMahjong.DiscardUnknown(m)
}

var xxx_messageInfo_PushGetOneMahjong proto.InternalMessageInfo

func (m *PushGetOneMahjong) GetTableRemainingMahjongsLen() int32 {
	if m != nil {
		return m.TableRemainingMahjongsLen
	}
	return 0
}

func (m *PushGetOneMahjong) GetIsSelf() bool {
	if m != nil {
		return m.IsSelf
	}
	return false
}

func (m *PushGetOneMahjong) GetMahjong() int32 {
	if m != nil {
		return m.Mahjong
	}
	return 0
}

// MSG_SHOW_ACTION_PUSH = 307; // 但玩家摸牌和打牌后 能做的动作
// SERVER PUSH : MSG_ID 307
// 7. 推送 玩家可以显示的动作
type PushShowAction struct {
	Chi                  bool          `protobuf:"varint,1,opt,name=chi,proto3" json:"chi,omitempty"`
	Peng                 bool          `protobuf:"varint,2,opt,name=peng,proto3" json:"peng,omitempty"`
	Ting                 bool          `protobuf:"varint,4,opt,name=ting,proto3" json:"ting,omitempty"`
	Hu                   bool          `protobuf:"varint,5,opt,name=hu,proto3" json:"hu,omitempty"`
	Gang                 *GangDetail   `protobuf:"bytes,3,opt,name=gang,proto3" json:"gang,omitempty"`
	ChiDetail            *ChiDetail    `protobuf:"bytes,6,opt,name=chiDetail,proto3" json:"chiDetail,omitempty"`
	TingDetail           []*TingDetail `protobuf:"bytes,7,rep,name=tingDetail,proto3" json:"tingDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PushShowAction) Reset()         { *m = PushShowAction{} }
func (m *PushShowAction) String() string { return proto.CompactTextString(m) }
func (*PushShowAction) ProtoMessage()    {}
func (*PushShowAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{9}
}

func (m *PushShowAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushShowAction.Unmarshal(m, b)
}
func (m *PushShowAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushShowAction.Marshal(b, m, deterministic)
}
func (m *PushShowAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushShowAction.Merge(m, src)
}
func (m *PushShowAction) XXX_Size() int {
	return xxx_messageInfo_PushShowAction.Size(m)
}
func (m *PushShowAction) XXX_DiscardUnknown() {
	xxx_messageInfo_PushShowAction.DiscardUnknown(m)
}

var xxx_messageInfo_PushShowAction proto.InternalMessageInfo

func (m *PushShowAction) GetChi() bool {
	if m != nil {
		return m.Chi
	}
	return false
}

func (m *PushShowAction) GetPeng() bool {
	if m != nil {
		return m.Peng
	}
	return false
}

func (m *PushShowAction) GetTing() bool {
	if m != nil {
		return m.Ting
	}
	return false
}

func (m *PushShowAction) GetHu() bool {
	if m != nil {
		return m.Hu
	}
	return false
}

func (m *PushShowAction) GetGang() *GangDetail {
	if m != nil {
		return m.Gang
	}
	return nil
}

func (m *PushShowAction) GetChiDetail() *ChiDetail {
	if m != nil {
		return m.ChiDetail
	}
	return nil
}

func (m *PushShowAction) GetTingDetail() []*TingDetail {
	if m != nil {
		return m.TingDetail
	}
	return nil
}

// MSH_RESET_TIME_PUSH = 308; // 重设时间
// SERVER PUSH : MSG_ID 308
type PushResetTime struct {
	Direction            string   `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushResetTime) Reset()         { *m = PushResetTime{} }
func (m *PushResetTime) String() string { return proto.CompactTextString(m) }
func (*PushResetTime) ProtoMessage()    {}
func (*PushResetTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{10}
}

func (m *PushResetTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushResetTime.Unmarshal(m, b)
}
func (m *PushResetTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushResetTime.Marshal(b, m, deterministic)
}
func (m *PushResetTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResetTime.Merge(m, src)
}
func (m *PushResetTime) XXX_Size() int {
	return xxx_messageInfo_PushResetTime.Size(m)
}
func (m *PushResetTime) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResetTime.DiscardUnknown(m)
}

var xxx_messageInfo_PushResetTime proto.InternalMessageInfo

func (m *PushResetTime) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

// MSG_SETTLEMENT_PUSH = 309; // 玩家胡牌 (结算信息)
// SERVER PUSH : MSG_ID 309
type Settlement struct {
	IsWin                bool             `protobuf:"varint,1,opt,name=isWin,proto3" json:"isWin,omitempty"`
	SettlementGold       string           `protobuf:"bytes,2,opt,name=settlementGold,proto3" json:"settlementGold,omitempty"`
	PlayerGold           string           `protobuf:"bytes,3,opt,name=playerGold,proto3" json:"playerGold,omitempty"`
	WinMahjongsInfo      *WinMahjongsInfo `protobuf:"bytes,4,opt,name=winMahjongsInfo,proto3" json:"winMahjongsInfo,omitempty"`
	LoseHandMahjongs     []int32          `protobuf:"varint,5,rep,packed,name=loseHandMahjongs,proto3" json:"loseHandMahjongs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Settlement) Reset()         { *m = Settlement{} }
func (m *Settlement) String() string { return proto.CompactTextString(m) }
func (*Settlement) ProtoMessage()    {}
func (*Settlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{11}
}

func (m *Settlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Settlement.Unmarshal(m, b)
}
func (m *Settlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Settlement.Marshal(b, m, deterministic)
}
func (m *Settlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Settlement.Merge(m, src)
}
func (m *Settlement) XXX_Size() int {
	return xxx_messageInfo_Settlement.Size(m)
}
func (m *Settlement) XXX_DiscardUnknown() {
	xxx_messageInfo_Settlement.DiscardUnknown(m)
}

var xxx_messageInfo_Settlement proto.InternalMessageInfo

func (m *Settlement) GetIsWin() bool {
	if m != nil {
		return m.IsWin
	}
	return false
}

func (m *Settlement) GetSettlementGold() string {
	if m != nil {
		return m.SettlementGold
	}
	return ""
}

func (m *Settlement) GetPlayerGold() string {
	if m != nil {
		return m.PlayerGold
	}
	return ""
}

func (m *Settlement) GetWinMahjongsInfo() *WinMahjongsInfo {
	if m != nil {
		return m.WinMahjongsInfo
	}
	return nil
}

func (m *Settlement) GetLoseHandMahjongs() []int32 {
	if m != nil {
		return m.LoseHandMahjongs
	}
	return nil
}

// SERVER PUSH : MSG_ID 500  // 服务器断开指令
// 1.断开连接指令
type CloseConn struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseConn) Reset()         { *m = CloseConn{} }
func (m *CloseConn) String() string { return proto.CompactTextString(m) }
func (*CloseConn) ProtoMessage()    {}
func (*CloseConn) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{12}
}

func (m *CloseConn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseConn.Unmarshal(m, b)
}
func (m *CloseConn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseConn.Marshal(b, m, deterministic)
}
func (m *CloseConn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseConn.Merge(m, src)
}
func (m *CloseConn) XXX_Size() int {
	return xxx_messageInfo_CloseConn.Size(m)
}
func (m *CloseConn) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseConn.DiscardUnknown(m)
}

var xxx_messageInfo_CloseConn proto.InternalMessageInfo

func (m *CloseConn) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CloseConn) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// SERVER PUSH : MSG_ID 501  // 服务器错误指令
// 1.服务器错误指令
type ErrMsg struct {
	MsgId                int32    `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrMsg) Reset()         { *m = ErrMsg{} }
func (m *ErrMsg) String() string { return proto.CompactTextString(m) }
func (*ErrMsg) ProtoMessage()    {}
func (*ErrMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{13}
}

func (m *ErrMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrMsg.Unmarshal(m, b)
}
func (m *ErrMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrMsg.Marshal(b, m, deterministic)
}
func (m *ErrMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrMsg.Merge(m, src)
}
func (m *ErrMsg) XXX_Size() int {
	return xxx_messageInfo_ErrMsg.Size(m)
}
func (m *ErrMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ErrMsg proto.InternalMessageInfo

func (m *ErrMsg) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *ErrMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//
//IsRobot           bool
//PlayerInfos       *PlayerInfo
//HandMahjongs      []int32  // 手牌
//PengMahjongs      []int32  // 碰牌
//ChiMahjongs       []string // 吃牌 ["11,12,13","12,13,14","14,15,16"] 字符串
//GangMahjongs      []int32  // 杠牌
//AnGangThreeMahjongs []int32  // 暗杠牌
//Village             bool     // 是否是庄
//Listen              bool     // 是否报听
type GamePlayer struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	HandMahjongs         []int32     `protobuf:"varint,2,rep,packed,name=handMahjongs,proto3" json:"handMahjongs,omitempty"`
	DoubleMahjongs       []int32     `protobuf:"varint,3,rep,packed,name=doubleMahjongs,proto3" json:"doubleMahjongs,omitempty"`
	EatMahjongs          []int32     `protobuf:"varint,4,rep,packed,name=eatMahjongs,proto3" json:"eatMahjongs,omitempty"`
	ThreeMahjongs        []int32     `protobuf:"varint,5,rep,packed,name=threeMahjongs,proto3" json:"threeMahjongs,omitempty"`
	DeepThreeMahjongs    []int32     `protobuf:"varint,6,rep,packed,name=deepThreeMahjongs,proto3" json:"deepThreeMahjongs,omitempty"`
	IsVillage            bool        `protobuf:"varint,7,opt,name=isVillage,proto3" json:"isVillage,omitempty"`
	IsListen             bool        `protobuf:"varint,8,opt,name=isListen,proto3" json:"isListen,omitempty"`
	WindDirection        string      `protobuf:"bytes,9,opt,name=windDirection,proto3" json:"windDirection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GamePlayer) Reset()         { *m = GamePlayer{} }
func (m *GamePlayer) String() string { return proto.CompactTextString(m) }
func (*GamePlayer) ProtoMessage()    {}
func (*GamePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{14}
}

func (m *GamePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamePlayer.Unmarshal(m, b)
}
func (m *GamePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamePlayer.Marshal(b, m, deterministic)
}
func (m *GamePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamePlayer.Merge(m, src)
}
func (m *GamePlayer) XXX_Size() int {
	return xxx_messageInfo_GamePlayer.Size(m)
}
func (m *GamePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_GamePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_GamePlayer proto.InternalMessageInfo

func (m *GamePlayer) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *GamePlayer) GetHandMahjongs() []int32 {
	if m != nil {
		return m.HandMahjongs
	}
	return nil
}

func (m *GamePlayer) GetDoubleMahjongs() []int32 {
	if m != nil {
		return m.DoubleMahjongs
	}
	return nil
}

func (m *GamePlayer) GetEatMahjongs() []int32 {
	if m != nil {
		return m.EatMahjongs
	}
	return nil
}

func (m *GamePlayer) GetThreeMahjongs() []int32 {
	if m != nil {
		return m.ThreeMahjongs
	}
	return nil
}

func (m *GamePlayer) GetDeepThreeMahjongs() []int32 {
	if m != nil {
		return m.DeepThreeMahjongs
	}
	return nil
}

func (m *GamePlayer) GetIsVillage() bool {
	if m != nil {
		return m.IsVillage
	}
	return false
}

func (m *GamePlayer) GetIsListen() bool {
	if m != nil {
		return m.IsListen
	}
	return false
}

func (m *GamePlayer) GetWindDirection() string {
	if m != nil {
		return m.WindDirection
	}
	return ""
}

// 1. LoginResp   2.PlayerListPush
type PlayerInfo struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`
	PlayerImg            string   `protobuf:"bytes,3,opt,name=playerImg,proto3" json:"playerImg,omitempty"`
	Gold                 float64  `protobuf:"fixed64,4,opt,name=gold,proto3" json:"gold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{15}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PlayerInfo) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *PlayerInfo) GetPlayerImg() string {
	if m != nil {
		return m.PlayerImg
	}
	return ""
}

func (m *PlayerInfo) GetGold() float64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

// RoomClassifyPush
type RoomClassify struct {
	RoomType             int32    `protobuf:"varint,1,opt,name=roomType,proto3" json:"roomType,omitempty"`
	BottomPoint          float64  `protobuf:"fixed64,2,opt,name=bottomPoint,proto3" json:"bottomPoint,omitempty"`
	BottomEnterPoint     float64  `protobuf:"fixed64,3,opt,name=bottomEnterPoint,proto3" json:"bottomEnterPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomClassify) Reset()         { *m = RoomClassify{} }
func (m *RoomClassify) String() string { return proto.CompactTextString(m) }
func (*RoomClassify) ProtoMessage()    {}
func (*RoomClassify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{16}
}

func (m *RoomClassify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomClassify.Unmarshal(m, b)
}
func (m *RoomClassify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomClassify.Marshal(b, m, deterministic)
}
func (m *RoomClassify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomClassify.Merge(m, src)
}
func (m *RoomClassify) XXX_Size() int {
	return xxx_messageInfo_RoomClassify.Size(m)
}
func (m *RoomClassify) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomClassify.DiscardUnknown(m)
}

var xxx_messageInfo_RoomClassify proto.InternalMessageInfo

func (m *RoomClassify) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *RoomClassify) GetBottomPoint() float64 {
	if m != nil {
		return m.BottomPoint
	}
	return 0
}

func (m *RoomClassify) GetBottomEnterPoint() float64 {
	if m != nil {
		return m.BottomEnterPoint
	}
	return 0
}

// PushPlayRoom
type RoomPlayerInfo struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	WindDirection        string      `protobuf:"bytes,2,opt,name=windDirection,proto3" json:"windDirection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RoomPlayerInfo) Reset()         { *m = RoomPlayerInfo{} }
func (m *RoomPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*RoomPlayerInfo) ProtoMessage()    {}
func (*RoomPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{17}
}

func (m *RoomPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomPlayerInfo.Unmarshal(m, b)
}
func (m *RoomPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomPlayerInfo.Marshal(b, m, deterministic)
}
func (m *RoomPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomPlayerInfo.Merge(m, src)
}
func (m *RoomPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_RoomPlayerInfo.Size(m)
}
func (m *RoomPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomPlayerInfo proto.InternalMessageInfo

func (m *RoomPlayerInfo) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *RoomPlayerInfo) GetWindDirection() string {
	if m != nil {
		return m.WindDirection
	}
	return ""
}

// PushPlayerChangesMahjongs
type PlayerChangesMahjongs struct {
	//
	//OutChange    = 1  // 出牌
	//PengChange   = 2  // 碰
	//ChiChange    = 3  // 吃
	//GangChange   = 4  // 杠
	//TingChange   = 5  // 听
	//// HuChange     = 6  // 胡  先保留  胡牌可能需要单独发消息
	//FlowerChange = 10 // 花牌替换
	ChangeType           int32            `protobuf:"varint,1,opt,name=changeType,proto3" json:"changeType,omitempty"`
	HandMahjongs         []int32          `protobuf:"varint,2,rep,packed,name=handMahjongs,proto3" json:"handMahjongs,omitempty"`
	OutSideMahjongs      *OutSideMahjongs `protobuf:"bytes,3,opt,name=outSideMahjongs,proto3" json:"outSideMahjongs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PlayerChangesMahjongs) Reset()         { *m = PlayerChangesMahjongs{} }
func (m *PlayerChangesMahjongs) String() string { return proto.CompactTextString(m) }
func (*PlayerChangesMahjongs) ProtoMessage()    {}
func (*PlayerChangesMahjongs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{18}
}

func (m *PlayerChangesMahjongs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerChangesMahjongs.Unmarshal(m, b)
}
func (m *PlayerChangesMahjongs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerChangesMahjongs.Marshal(b, m, deterministic)
}
func (m *PlayerChangesMahjongs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerChangesMahjongs.Merge(m, src)
}
func (m *PlayerChangesMahjongs) XXX_Size() int {
	return xxx_messageInfo_PlayerChangesMahjongs.Size(m)
}
func (m *PlayerChangesMahjongs) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerChangesMahjongs.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerChangesMahjongs proto.InternalMessageInfo

func (m *PlayerChangesMahjongs) GetChangeType() int32 {
	if m != nil {
		return m.ChangeType
	}
	return 0
}

func (m *PlayerChangesMahjongs) GetHandMahjongs() []int32 {
	if m != nil {
		return m.HandMahjongs
	}
	return nil
}

func (m *PlayerChangesMahjongs) GetOutSideMahjongs() *OutSideMahjongs {
	if m != nil {
		return m.OutSideMahjongs
	}
	return nil
}

// PushOtherPlayerChangesMahjongs
type OtherPlayerChangesMahjongs struct {
	//
	//OutChange    = 1  // 出牌
	//PengChange   = 2  // 碰
	//ChiChange    = 3  // 吃
	//GangChange   = 4  // 杠
	//TingChange   = 5  // 听
	////HuChange     = 6  // 胡 先保留  胡牌可能需要单独发消息
	//FlowerChange = 10 // 花牌替换
	ChangeType           int32            `protobuf:"varint,1,opt,name=changeType,proto3" json:"changeType,omitempty"`
	OtherMahjongsLen     int32            `protobuf:"varint,2,opt,name=otherMahjongsLen,proto3" json:"otherMahjongsLen,omitempty"`
	OtherOutSideMahjongs *OutSideMahjongs `protobuf:"bytes,3,opt,name=OtherOutSideMahjongs,proto3" json:"OtherOutSideMahjongs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OtherPlayerChangesMahjongs) Reset()         { *m = OtherPlayerChangesMahjongs{} }
func (m *OtherPlayerChangesMahjongs) String() string { return proto.CompactTextString(m) }
func (*OtherPlayerChangesMahjongs) ProtoMessage()    {}
func (*OtherPlayerChangesMahjongs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{19}
}

func (m *OtherPlayerChangesMahjongs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtherPlayerChangesMahjongs.Unmarshal(m, b)
}
func (m *OtherPlayerChangesMahjongs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtherPlayerChangesMahjongs.Marshal(b, m, deterministic)
}
func (m *OtherPlayerChangesMahjongs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtherPlayerChangesMahjongs.Merge(m, src)
}
func (m *OtherPlayerChangesMahjongs) XXX_Size() int {
	return xxx_messageInfo_OtherPlayerChangesMahjongs.Size(m)
}
func (m *OtherPlayerChangesMahjongs) XXX_DiscardUnknown() {
	xxx_messageInfo_OtherPlayerChangesMahjongs.DiscardUnknown(m)
}

var xxx_messageInfo_OtherPlayerChangesMahjongs proto.InternalMessageInfo

func (m *OtherPlayerChangesMahjongs) GetChangeType() int32 {
	if m != nil {
		return m.ChangeType
	}
	return 0
}

func (m *OtherPlayerChangesMahjongs) GetOtherMahjongsLen() int32 {
	if m != nil {
		return m.OtherMahjongsLen
	}
	return 0
}

func (m *OtherPlayerChangesMahjongs) GetOtherOutSideMahjongs() *OutSideMahjongs {
	if m != nil {
		return m.OtherOutSideMahjongs
	}
	return nil
}

// 双方都可见的牌信息
// PushPlayerChangesMahjongs.PlayerChangesMahjongs.OutSideMahjongs
// PushOtherPlayerChangesMahjongs.OtherPlayerChangesMahjongs.OutSideMahjongs
type OutSideMahjongs struct {
	TableRemainingMahjongsLen int32    `protobuf:"varint,1,opt,name=tableRemainingMahjongsLen,proto3" json:"tableRemainingMahjongsLen,omitempty"`
	FlowerMahjongs            []int32  `protobuf:"varint,2,rep,packed,name=flowerMahjongs,proto3" json:"flowerMahjongs,omitempty"`
	PengMahjongs              []int32  `protobuf:"varint,3,rep,packed,name=pengMahjongs,proto3" json:"pengMahjongs,omitempty"`
	EatMahjongs               []int32  `protobuf:"varint,4,rep,packed,name=eatMahjongs,proto3" json:"eatMahjongs,omitempty"`
	GangMahjongs              []int32  `protobuf:"varint,5,rep,packed,name=gangMahjongs,proto3" json:"gangMahjongs,omitempty"`
	AnGangMahjongs            []int32  `protobuf:"varint,6,rep,packed,name=anGangMahjongs,proto3" json:"anGangMahjongs,omitempty"`
	ThrowMahjongs             []int32  `protobuf:"varint,7,rep,packed,name=throwMahjongs,proto3" json:"throwMahjongs,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *OutSideMahjongs) Reset()         { *m = OutSideMahjongs{} }
func (m *OutSideMahjongs) String() string { return proto.CompactTextString(m) }
func (*OutSideMahjongs) ProtoMessage()    {}
func (*OutSideMahjongs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{20}
}

func (m *OutSideMahjongs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutSideMahjongs.Unmarshal(m, b)
}
func (m *OutSideMahjongs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutSideMahjongs.Marshal(b, m, deterministic)
}
func (m *OutSideMahjongs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutSideMahjongs.Merge(m, src)
}
func (m *OutSideMahjongs) XXX_Size() int {
	return xxx_messageInfo_OutSideMahjongs.Size(m)
}
func (m *OutSideMahjongs) XXX_DiscardUnknown() {
	xxx_messageInfo_OutSideMahjongs.DiscardUnknown(m)
}

var xxx_messageInfo_OutSideMahjongs proto.InternalMessageInfo

func (m *OutSideMahjongs) GetTableRemainingMahjongsLen() int32 {
	if m != nil {
		return m.TableRemainingMahjongsLen
	}
	return 0
}

func (m *OutSideMahjongs) GetFlowerMahjongs() []int32 {
	if m != nil {
		return m.FlowerMahjongs
	}
	return nil
}

func (m *OutSideMahjongs) GetPengMahjongs() []int32 {
	if m != nil {
		return m.PengMahjongs
	}
	return nil
}

func (m *OutSideMahjongs) GetEatMahjongs() []int32 {
	if m != nil {
		return m.EatMahjongs
	}
	return nil
}

func (m *OutSideMahjongs) GetGangMahjongs() []int32 {
	if m != nil {
		return m.GangMahjongs
	}
	return nil
}

func (m *OutSideMahjongs) GetAnGangMahjongs() []int32 {
	if m != nil {
		return m.AnGangMahjongs
	}
	return nil
}

func (m *OutSideMahjongs) GetThrowMahjongs() []int32 {
	if m != nil {
		return m.ThrowMahjongs
	}
	return nil
}

// 听牌的详细数据
type TingDetail struct {
	OutCard              int32             `protobuf:"varint,1,opt,name=outCard,proto3" json:"outCard,omitempty"`
	TingCardDetail       []*TingCardDetail `protobuf:"bytes,2,rep,name=tingCardDetail,proto3" json:"tingCardDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TingDetail) Reset()         { *m = TingDetail{} }
func (m *TingDetail) String() string { return proto.CompactTextString(m) }
func (*TingDetail) ProtoMessage()    {}
func (*TingDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{21}
}

func (m *TingDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TingDetail.Unmarshal(m, b)
}
func (m *TingDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TingDetail.Marshal(b, m, deterministic)
}
func (m *TingDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TingDetail.Merge(m, src)
}
func (m *TingDetail) XXX_Size() int {
	return xxx_messageInfo_TingDetail.Size(m)
}
func (m *TingDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TingDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TingDetail proto.InternalMessageInfo

func (m *TingDetail) GetOutCard() int32 {
	if m != nil {
		return m.OutCard
	}
	return 0
}

func (m *TingDetail) GetTingCardDetail() []*TingCardDetail {
	if m != nil {
		return m.TingCardDetail
	}
	return nil
}

// 吃牌的详细数据
type ChiDetail struct {
	OutCard              int32    `protobuf:"varint,1,opt,name=outCard,proto3" json:"outCard,omitempty"`
	ChiType              []int32  `protobuf:"varint,2,rep,packed,name=chiType,proto3" json:"chiType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChiDetail) Reset()         { *m = ChiDetail{} }
func (m *ChiDetail) String() string { return proto.CompactTextString(m) }
func (*ChiDetail) ProtoMessage()    {}
func (*ChiDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{22}
}

func (m *ChiDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChiDetail.Unmarshal(m, b)
}
func (m *ChiDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChiDetail.Marshal(b, m, deterministic)
}
func (m *ChiDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChiDetail.Merge(m, src)
}
func (m *ChiDetail) XXX_Size() int {
	return xxx_messageInfo_ChiDetail.Size(m)
}
func (m *ChiDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ChiDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ChiDetail proto.InternalMessageInfo

func (m *ChiDetail) GetOutCard() int32 {
	if m != nil {
		return m.OutCard
	}
	return 0
}

func (m *ChiDetail) GetChiType() []int32 {
	if m != nil {
		return m.ChiType
	}
	return nil
}

// 杠牌的详细数据
type GangDetail struct {
	Gang                 bool     `protobuf:"varint,1,opt,name=gang,proto3" json:"gang,omitempty"`
	OutCard              int32    `protobuf:"varint,2,opt,name=outCard,proto3" json:"outCard,omitempty"`
	GangType             int32    `protobuf:"varint,3,opt,name=gangType,proto3" json:"gangType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GangDetail) Reset()         { *m = GangDetail{} }
func (m *GangDetail) String() string { return proto.CompactTextString(m) }
func (*GangDetail) ProtoMessage()    {}
func (*GangDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{23}
}

func (m *GangDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GangDetail.Unmarshal(m, b)
}
func (m *GangDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GangDetail.Marshal(b, m, deterministic)
}
func (m *GangDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GangDetail.Merge(m, src)
}
func (m *GangDetail) XXX_Size() int {
	return xxx_messageInfo_GangDetail.Size(m)
}
func (m *GangDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_GangDetail.DiscardUnknown(m)
}

var xxx_messageInfo_GangDetail proto.InternalMessageInfo

func (m *GangDetail) GetGang() bool {
	if m != nil {
		return m.Gang
	}
	return false
}

func (m *GangDetail) GetOutCard() int32 {
	if m != nil {
		return m.OutCard
	}
	return 0
}

func (m *GangDetail) GetGangType() int32 {
	if m != nil {
		return m.GangType
	}
	return 0
}

// 听牌的详细数据
type TingCardDetail struct {
	TingCard             int32    `protobuf:"varint,1,opt,name=tingCard,proto3" json:"tingCard,omitempty"`
	TingRemainingNum     int32    `protobuf:"varint,2,opt,name=tingRemainingNum,proto3" json:"tingRemainingNum,omitempty"`
	Fang                 int32    `protobuf:"varint,3,opt,name=fang,proto3" json:"fang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TingCardDetail) Reset()         { *m = TingCardDetail{} }
func (m *TingCardDetail) String() string { return proto.CompactTextString(m) }
func (*TingCardDetail) ProtoMessage()    {}
func (*TingCardDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{24}
}

func (m *TingCardDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TingCardDetail.Unmarshal(m, b)
}
func (m *TingCardDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TingCardDetail.Marshal(b, m, deterministic)
}
func (m *TingCardDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TingCardDetail.Merge(m, src)
}
func (m *TingCardDetail) XXX_Size() int {
	return xxx_messageInfo_TingCardDetail.Size(m)
}
func (m *TingCardDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TingCardDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TingCardDetail proto.InternalMessageInfo

func (m *TingCardDetail) GetTingCard() int32 {
	if m != nil {
		return m.TingCard
	}
	return 0
}

func (m *TingCardDetail) GetTingRemainingNum() int32 {
	if m != nil {
		return m.TingRemainingNum
	}
	return 0
}

func (m *TingCardDetail) GetFang() int32 {
	if m != nil {
		return m.Fang
	}
	return 0
}

// 赢方的麻将信息
type WinMahjongsInfo struct {
	HandMahjongs         []int32   `protobuf:"varint,1,rep,packed,name=handMahjongs,proto3" json:"handMahjongs,omitempty"`
	PengMahjongs         []int32   `protobuf:"varint,2,rep,packed,name=PengMahjongs,proto3" json:"PengMahjongs,omitempty"`
	ChiMahjongs          []int32   `protobuf:"varint,3,rep,packed,name=ChiMahjongs,proto3" json:"ChiMahjongs,omitempty"`
	GangMahjongs         []int32   `protobuf:"varint,4,rep,packed,name=GangMahjongs,proto3" json:"GangMahjongs,omitempty"`
	AnGangMahjongs       []int32   `protobuf:"varint,5,rep,packed,name=AnGangMahjongs,proto3" json:"AnGangMahjongs,omitempty"`
	HuCard               int32     `protobuf:"varint,6,opt,name=huCard,proto3" json:"huCard,omitempty"`
	FangInfo             *FangInfo `protobuf:"bytes,7,opt,name=fangInfo,proto3" json:"fangInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WinMahjongsInfo) Reset()         { *m = WinMahjongsInfo{} }
func (m *WinMahjongsInfo) String() string { return proto.CompactTextString(m) }
func (*WinMahjongsInfo) ProtoMessage()    {}
func (*WinMahjongsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{25}
}

func (m *WinMahjongsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WinMahjongsInfo.Unmarshal(m, b)
}
func (m *WinMahjongsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WinMahjongsInfo.Marshal(b, m, deterministic)
}
func (m *WinMahjongsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WinMahjongsInfo.Merge(m, src)
}
func (m *WinMahjongsInfo) XXX_Size() int {
	return xxx_messageInfo_WinMahjongsInfo.Size(m)
}
func (m *WinMahjongsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WinMahjongsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WinMahjongsInfo proto.InternalMessageInfo

func (m *WinMahjongsInfo) GetHandMahjongs() []int32 {
	if m != nil {
		return m.HandMahjongs
	}
	return nil
}

func (m *WinMahjongsInfo) GetPengMahjongs() []int32 {
	if m != nil {
		return m.PengMahjongs
	}
	return nil
}

func (m *WinMahjongsInfo) GetChiMahjongs() []int32 {
	if m != nil {
		return m.ChiMahjongs
	}
	return nil
}

func (m *WinMahjongsInfo) GetGangMahjongs() []int32 {
	if m != nil {
		return m.GangMahjongs
	}
	return nil
}

func (m *WinMahjongsInfo) GetAnGangMahjongs() []int32 {
	if m != nil {
		return m.AnGangMahjongs
	}
	return nil
}

func (m *WinMahjongsInfo) GetHuCard() int32 {
	if m != nil {
		return m.HuCard
	}
	return 0
}

func (m *WinMahjongsInfo) GetFangInfo() *FangInfo {
	if m != nil {
		return m.FangInfo
	}
	return nil
}

// 赢牌的番数信息
type FangInfo struct {
	FangTotal            int32         `protobuf:"varint,1,opt,name=FangTotal,proto3" json:"FangTotal,omitempty"`
	FangDetails          []*FangDetail `protobuf:"bytes,2,rep,name=fangDetails,proto3" json:"fangDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FangInfo) Reset()         { *m = FangInfo{} }
func (m *FangInfo) String() string { return proto.CompactTextString(m) }
func (*FangInfo) ProtoMessage()    {}
func (*FangInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{26}
}

func (m *FangInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FangInfo.Unmarshal(m, b)
}
func (m *FangInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FangInfo.Marshal(b, m, deterministic)
}
func (m *FangInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FangInfo.Merge(m, src)
}
func (m *FangInfo) XXX_Size() int {
	return xxx_messageInfo_FangInfo.Size(m)
}
func (m *FangInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FangInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FangInfo proto.InternalMessageInfo

func (m *FangInfo) GetFangTotal() int32 {
	if m != nil {
		return m.FangTotal
	}
	return 0
}

func (m *FangInfo) GetFangDetails() []*FangDetail {
	if m != nil {
		return m.FangDetails
	}
	return nil
}

// 番数 //
type FangDetail struct {
	FangName             string   `protobuf:"bytes,1,opt,name=fangName,proto3" json:"fangName,omitempty"`
	FangNum              int32    `protobuf:"varint,2,opt,name=fangNum,proto3" json:"fangNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FangDetail) Reset()         { *m = FangDetail{} }
func (m *FangDetail) String() string { return proto.CompactTextString(m) }
func (*FangDetail) ProtoMessage()    {}
func (*FangDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{27}
}

func (m *FangDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FangDetail.Unmarshal(m, b)
}
func (m *FangDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FangDetail.Marshal(b, m, deterministic)
}
func (m *FangDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FangDetail.Merge(m, src)
}
func (m *FangDetail) XXX_Size() int {
	return xxx_messageInfo_FangDetail.Size(m)
}
func (m *FangDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_FangDetail.DiscardUnknown(m)
}

var xxx_messageInfo_FangDetail proto.InternalMessageInfo

func (m *FangDetail) GetFangName() string {
	if m != nil {
		return m.FangName
	}
	return ""
}

func (m *FangDetail) GetFangNum() int32 {
	if m != nil {
		return m.FangNum
	}
	return 0
}

func init() {
	proto.RegisterType((*PONG)(nil), "mproto.PONG")
	proto.RegisterType((*RespLogin)(nil), "mproto.RespLogin")
	proto.RegisterType((*PushRoomClassify)(nil), "mproto.PushRoomClassify")
	proto.RegisterType((*PushPlayRoom)(nil), "mproto.PushPlayRoom")
	proto.RegisterType((*PushDice)(nil), "mproto.PushDice")
	proto.RegisterType((*PushLicensing)(nil), "mproto.PushLicensing")
	proto.RegisterType((*PushPlayerChangesMahjongs)(nil), "mproto.PushPlayerChangesMahjongs")
	proto.RegisterType((*PushOtherPlayerChangesMahjongs)(nil), "mproto.PushOtherPlayerChangesMahjongs")
	proto.RegisterType((*PushGetOneMahjong)(nil), "mproto.PushGetOneMahjong")
	proto.RegisterType((*PushShowAction)(nil), "mproto.PushShowAction")
	proto.RegisterType((*PushResetTime)(nil), "mproto.PushResetTime")
	proto.RegisterType((*Settlement)(nil), "mproto.Settlement")
	proto.RegisterType((*CloseConn)(nil), "mproto.CloseConn")
	proto.RegisterType((*ErrMsg)(nil), "mproto.ErrMsg")
	proto.RegisterType((*GamePlayer)(nil), "mproto.GamePlayer")
	proto.RegisterType((*PlayerInfo)(nil), "mproto.PlayerInfo")
	proto.RegisterType((*RoomClassify)(nil), "mproto.RoomClassify")
	proto.RegisterType((*RoomPlayerInfo)(nil), "mproto.RoomPlayerInfo")
	proto.RegisterType((*PlayerChangesMahjongs)(nil), "mproto.PlayerChangesMahjongs")
	proto.RegisterType((*OtherPlayerChangesMahjongs)(nil), "mproto.OtherPlayerChangesMahjongs")
	proto.RegisterType((*OutSideMahjongs)(nil), "mproto.OutSideMahjongs")
	proto.RegisterType((*TingDetail)(nil), "mproto.TingDetail")
	proto.RegisterType((*ChiDetail)(nil), "mproto.ChiDetail")
	proto.RegisterType((*GangDetail)(nil), "mproto.GangDetail")
	proto.RegisterType((*TingCardDetail)(nil), "mproto.TingCardDetail")
	proto.RegisterType((*WinMahjongsInfo)(nil), "mproto.WinMahjongsInfo")
	proto.RegisterType((*FangInfo)(nil), "mproto.FangInfo")
	proto.RegisterType((*FangDetail)(nil), "mproto.FangDetail")
}

func init() { proto.RegisterFile("resp.proto", fileDescriptor_3c5365792f61ddff) }

var fileDescriptor_3c5365792f61ddff = []byte{
	// 1244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x96, 0x93, 0x34, 0x3f, 0xa7, 0xd9, 0xa4, 0x3b, 0x2a, 0x8b, 0xb7, 0x82, 0xaa, 0x1a, 0xa1,
	0xaa, 0x5a, 0x2d, 0x85, 0x2d, 0x3f, 0xe2, 0x02, 0x81, 0x4a, 0xba, 0x84, 0x15, 0xd9, 0x36, 0x9a,
	0x46, 0xbb, 0x77, 0x08, 0x37, 0x9e, 0xd8, 0xb3, 0xb2, 0xc7, 0x91, 0xed, 0x50, 0xca, 0x15, 0x12,
	0xd7, 0xbc, 0x02, 0xaf, 0xc0, 0x15, 0x0f, 0xc3, 0x2d, 0x37, 0xbc, 0x06, 0x3a, 0xe3, 0x19, 0xff,
	0x25, 0x5d, 0xca, 0x72, 0xe5, 0x39, 0xdf, 0x7c, 0x73, 0xce, 0xcc, 0x99, 0x6f, 0xce, 0x31, 0x40,
	0xcc, 0x93, 0xe5, 0xf1, 0x32, 0x8e, 0xd2, 0x88, 0xb4, 0x43, 0xf5, 0xa5, 0x7b, 0xd0, 0x9a, 0x5e,
	0x9c, 0x8f, 0x09, 0x81, 0x56, 0x2a, 0x42, 0x6e, 0x5b, 0x07, 0xd6, 0x51, 0x93, 0xa9, 0x31, 0xfd,
	0x12, 0x7a, 0x8c, 0x27, 0xcb, 0x49, 0xe4, 0x09, 0x49, 0x4e, 0x00, 0x96, 0x81, 0x73, 0xc3, 0xe3,
	0x67, 0x72, 0x11, 0x29, 0xda, 0xf6, 0x09, 0x39, 0xce, 0xbc, 0x1c, 0x4f, 0xf3, 0x19, 0x56, 0x62,
	0xd1, 0x09, 0xec, 0x4c, 0x57, 0x89, 0xcf, 0xa2, 0x28, 0x1c, 0x05, 0x4e, 0x92, 0x88, 0xc5, 0x0d,
	0xf9, 0x0c, 0xfa, 0x71, 0xc9, 0xb6, 0xad, 0x83, 0xe6, 0xd1, 0xf6, 0xc9, 0xae, 0xf1, 0x54, 0xe6,
	0xb2, 0x0a, 0x93, 0xfe, 0x6c, 0x41, 0x1f, 0xdd, 0x61, 0x30, 0xa4, 0x6d, 0x70, 0x65, 0xdd, 0xcd,
	0x15, 0xf9, 0x14, 0x00, 0xed, 0x6c, 0xdb, 0x76, 0x43, 0x6d, 0xe1, 0x41, 0x79, 0x5d, 0xf9, 0x40,
	0x05, 0x93, 0x7e, 0x0f, 0x5d, 0xdc, 0xc1, 0x99, 0x98, 0x73, 0xb2, 0x0b, 0x5b, 0xae, 0x98, 0xf3,
	0x27, 0x2a, 0xec, 0x16, 0xcb, 0x0c, 0x83, 0x9e, 0xd8, 0x8d, 0x02, 0x3d, 0x21, 0x47, 0x30, 0xfc,
	0x41, 0x04, 0x81, 0xe3, 0x71, 0xed, 0xd8, 0xb5, 0x9b, 0x07, 0xd6, 0x51, 0x8f, 0xd5, 0x61, 0xfa,
	0x09, 0xdc, 0xc3, 0x08, 0x13, 0x31, 0xe7, 0x32, 0x11, 0xd2, 0x23, 0xef, 0xc1, 0x3d, 0xdf, 0x91,
	0x6e, 0xc0, 0x9f, 0x3b, 0xfe, 0xab, 0x48, 0x7a, 0x2a, 0x61, 0x5b, 0xac, 0x0a, 0x52, 0x17, 0x1e,
	0x9a, 0xd4, 0xf0, 0x78, 0xe4, 0x3b, 0xd2, 0xe3, 0x89, 0x9e, 0x4b, 0xc8, 0x18, 0x86, 0xf3, 0x2a,
	0xa4, 0x53, 0xf5, 0x6e, 0xf5, 0xfe, 0x6a, 0xeb, 0x58, 0x7d, 0x15, 0x95, 0xb0, 0x8f, 0x51, 0x2e,
	0x52, 0x9f, 0xc7, 0x9b, 0x43, 0x4d, 0x6e, 0x0b, 0x45, 0x4d, 0xa8, 0xdb, 0x17, 0xaf, 0xc7, 0xfb,
	0xc5, 0x82, 0xfb, 0x18, 0x70, 0xcc, 0xd3, 0x0b, 0x69, 0xce, 0x4a, 0x3e, 0x87, 0x87, 0xa9, 0x73,
	0x15, 0x70, 0xc6, 0x43, 0x47, 0x48, 0x21, 0x3d, 0xc3, 0x9f, 0x70, 0xa9, 0x2f, 0xe3, 0x76, 0x02,
	0x79, 0x00, 0x6d, 0x91, 0x5c, 0xf2, 0x60, 0xa1, 0x6e, 0xa8, 0xcb, 0xb4, 0x45, 0x6c, 0xe8, 0x84,
	0x3a, 0xc3, 0x4d, 0xe5, 0xc3, 0x98, 0xf4, 0x6f, 0x0b, 0x06, 0xb8, 0x8b, 0x4b, 0x3f, 0xba, 0x3e,
	0x9d, 0xa7, 0x22, 0x92, 0x64, 0x07, 0x9a, 0x73, 0x5f, 0xa8, 0x60, 0x5d, 0x86, 0x43, 0x7c, 0x3f,
	0x4b, 0x2e, 0x3d, 0xed, 0x54, 0x8d, 0xb3, 0x37, 0x25, 0x3d, 0xbb, 0x95, 0x61, 0x38, 0x26, 0x03,
	0x68, 0xf8, 0x2b, 0x7b, 0x4b, 0x21, 0x0d, 0x7f, 0x45, 0x0e, 0xa1, 0xe5, 0x39, 0x3a, 0x66, 0xe9,
	0x41, 0x8d, 0x1d, 0xe9, 0x9d, 0xf1, 0xd4, 0x11, 0x01, 0x53, 0xf3, 0xe4, 0x03, 0xe8, 0xcd, 0x7d,
	0x91, 0x41, 0x76, 0x5b, 0x91, 0xef, 0x1b, 0xf2, 0xc8, 0x4c, 0xb0, 0x82, 0x83, 0xef, 0x15, 0x03,
	0xea, 0x15, 0x1d, 0x25, 0xf1, 0xdc, 0xfd, 0x2c, 0x9f, 0x61, 0x25, 0x16, 0x7d, 0x3f, 0x13, 0x1f,
	0xe3, 0x09, 0x4f, 0x67, 0x22, 0xe4, 0xe4, 0x1d, 0xe8, 0xb9, 0x22, 0xe6, 0xea, 0xd0, 0xea, 0xb4,
	0x3d, 0x56, 0x00, 0xf4, 0x4f, 0x0b, 0xe0, 0x92, 0xa7, 0x69, 0xc0, 0x43, 0x2e, 0x53, 0x94, 0xbe,
	0x48, 0x5e, 0x0a, 0xa9, 0xd3, 0x92, 0x19, 0xe4, 0x10, 0x06, 0x49, 0xce, 0x19, 0x47, 0x81, 0xab,
	0x52, 0xd4, 0x63, 0x35, 0x94, 0xec, 0x9b, 0xfa, 0xa2, 0x38, 0xd9, 0xeb, 0x28, 0x21, 0xe4, 0x14,
	0x86, 0xd7, 0x42, 0x9a, 0x9b, 0x54, 0x45, 0xa8, 0xa5, 0xd2, 0xf0, 0xb6, 0x39, 0xd4, 0xcb, 0xea,
	0x34, 0xab, 0xf3, 0xc9, 0x23, 0xd8, 0x09, 0xa2, 0x84, 0x7f, 0xe3, 0x48, 0x37, 0x57, 0xe7, 0x96,
	0x7a, 0x4d, 0x6b, 0x38, 0x7d, 0x02, 0xbd, 0x11, 0x82, 0xa3, 0x48, 0x4a, 0xbc, 0xc8, 0x79, 0xe4,
	0x72, 0x2d, 0x2e, 0x35, 0x46, 0x09, 0x84, 0x89, 0xa7, 0x0f, 0x83, 0x43, 0xfa, 0x21, 0xb4, 0x9f,
	0xc6, 0xf1, 0xf3, 0xc4, 0xc3, 0x4c, 0x84, 0x89, 0xf7, 0xcc, 0x35, 0xa5, 0x41, 0x19, 0x1b, 0x56,
	0xfc, 0xd5, 0x00, 0x18, 0x3b, 0xa1, 0x7e, 0xfd, 0x6f, 0x52, 0x62, 0x09, 0x85, 0xbe, 0x5f, 0x3e,
	0x4f, 0x43, 0x9d, 0xa7, 0x82, 0xe1, 0x15, 0xb8, 0xd1, 0xea, 0x2a, 0xaf, 0x16, 0x89, 0xdd, 0x54,
	0xac, 0x1a, 0x4a, 0x0e, 0x60, 0x9b, 0x3b, 0x69, 0x4e, 0x6a, 0x29, 0x52, 0x19, 0xc2, 0x62, 0x94,
	0xfa, 0x31, 0xe7, 0xb5, 0xf4, 0x55, 0x41, 0xf2, 0x18, 0xee, 0xbb, 0x9c, 0x2f, 0x67, 0x15, 0x66,
	0x5b, 0x31, 0xd7, 0x27, 0x50, 0x63, 0x22, 0x79, 0x91, 0x95, 0x41, 0xbb, 0xa3, 0xa4, 0x53, 0x00,
	0x64, 0x0f, 0xba, 0x22, 0x99, 0x88, 0x24, 0xe5, 0xd2, 0xee, 0xaa, 0xc9, 0xdc, 0xc6, 0xdd, 0x5c,
	0x0b, 0xe9, 0x9e, 0xe5, 0x0a, 0xed, 0xa9, 0xd4, 0x56, 0x41, 0xfa, 0x13, 0x40, 0x91, 0x3b, 0xf4,
	0xb7, 0x34, 0x25, 0x38, 0x13, 0x74, 0x6e, 0x17, 0x12, 0x3c, 0x77, 0x42, 0xae, 0xef, 0xa9, 0x84,
	0xe0, 0x4e, 0x35, 0x37, 0xf4, 0xb4, 0x42, 0x0b, 0x00, 0x45, 0xe2, 0xa1, 0x74, 0x51, 0x95, 0x16,
	0x53, 0x63, 0xfa, 0x23, 0xf4, 0x2b, 0xcd, 0x6f, 0x0f, 0xba, 0xd8, 0x4d, 0x66, 0x37, 0x4b, 0x23,
	0xa6, 0xdc, 0xc6, 0xec, 0x5f, 0x45, 0x69, 0x1a, 0x85, 0xd3, 0x48, 0xc8, 0x54, 0x85, 0xb7, 0x58,
	0x19, 0x42, 0xfd, 0x66, 0xe6, 0x53, 0x99, 0xf2, 0x38, 0xa3, 0x35, 0x15, 0x6d, 0x0d, 0xa7, 0xaf,
	0x60, 0x50, 0xed, 0x63, 0x6f, 0xa4, 0xae, 0xb5, 0x0c, 0x37, 0x36, 0x65, 0xf8, 0x37, 0x0b, 0xde,
	0xda, 0xdc, 0x0e, 0xf6, 0x01, 0xb2, 0x9a, 0x5e, 0x3a, 0x71, 0x09, 0xb9, 0x93, 0x7a, 0x4f, 0x61,
	0x18, 0xad, 0xd2, 0x4b, 0xe1, 0x96, 0xe5, 0x5b, 0x79, 0xf8, 0x17, 0xd5, 0x69, 0x56, 0xe7, 0xd3,
	0x3f, 0x2c, 0xd8, 0x7b, 0x4d, 0xd3, 0xfa, 0xb7, 0x5d, 0x3e, 0x82, 0x9d, 0x08, 0x57, 0x97, 0xfb,
	0x4c, 0xd6, 0xde, 0xd7, 0x70, 0xf2, 0x2d, 0xec, 0xaa, 0x48, 0x17, 0xff, 0x6d, 0xcb, 0x1b, 0x17,
	0xd1, 0xdf, 0x1b, 0x30, 0xac, 0x61, 0xff, 0xb3, 0xfb, 0x1d, 0xc2, 0x60, 0x11, 0x44, 0xd7, 0xc5,
	0x9e, 0x75, 0xca, 0x6b, 0x28, 0x5e, 0x0c, 0xb6, 0xb0, 0x5a, 0xc1, 0xa8, 0x60, 0x77, 0x28, 0x17,
	0x14, 0xfa, 0xd8, 0xbc, 0x6a, 0xd5, 0xa2, 0x82, 0xe1, 0x8e, 0x1c, 0x39, 0x2e, 0xb3, 0xb2, 0x4a,
	0x51, 0x43, 0x75, 0xe9, 0x89, 0xae, 0x73, 0x5a, 0x27, 0x2f, 0x3d, 0x05, 0x48, 0x17, 0x00, 0x45,
	0x6f, 0xc3, 0x9e, 0x1e, 0xad, 0xd2, 0x91, 0x13, 0x9b, 0x4a, 0x6c, 0x4c, 0xf2, 0x05, 0x0c, 0xb0,
	0xef, 0xe1, 0x58, 0x77, 0xc8, 0xda, 0x4f, 0xe0, 0xac, 0x32, 0xcb, 0x6a, 0x6c, 0xfc, 0x35, 0xce,
	0xbb, 0xee, 0x6b, 0xc2, 0xd8, 0xd0, 0x99, 0xfb, 0x42, 0xc9, 0x2a, 0xcb, 0xb3, 0x31, 0xe9, 0x0b,
	0xac, 0xfc, 0xf9, 0x46, 0x89, 0xfe, 0x0b, 0xc8, 0x3a, 0x67, 0xd6, 0xf1, 0x4b, 0x5e, 0x1b, 0x55,
	0xaf, 0x7b, 0xd0, 0x45, 0x86, 0x72, 0x9b, 0xfd, 0xab, 0xe4, 0x36, 0x0d, 0x60, 0x50, 0xdd, 0x3a,
	0xb2, 0xcd, 0xe6, 0x4d, 0xcd, 0x31, 0x36, 0x2a, 0x1b, 0xc7, 0xb9, 0x54, 0xce, 0x57, 0xa1, 0x51,
	0x76, 0x1d, 0xc7, 0x3d, 0x2e, 0x9c, 0xfc, 0xef, 0x48, 0x8d, 0xe9, 0xaf, 0x0d, 0x18, 0xd6, 0xda,
	0xee, 0xda, 0x9b, 0xb6, 0x36, 0xbc, 0x69, 0x0a, 0xfd, 0x69, 0x59, 0x5e, 0xfa, 0xdd, 0x4f, 0x6b,
	0xf2, 0x1a, 0xf9, 0xa2, 0xa6, 0xc0, 0x32, 0x84, 0x5e, 0x2a, 0xc2, 0xc9, 0x14, 0x58, 0xc1, 0x50,
	0x5e, 0xa7, 0x55, 0x79, 0x65, 0x22, 0xac, 0xa1, 0xf8, 0x5b, 0xe8, 0xaf, 0x54, 0x8e, 0xda, 0xea,
	0x7c, 0xda, 0x22, 0x8f, 0xa1, 0x8b, 0x27, 0x55, 0x35, 0xb3, 0xa3, 0xde, 0xf0, 0x8e, 0x91, 0xc8,
	0xd7, 0x1a, 0x67, 0x39, 0x83, 0x7e, 0x07, 0x5d, 0x83, 0x62, 0xb7, 0xc0, 0xf1, 0x2c, 0x4a, 0x9d,
	0x40, 0x27, 0xbe, 0x00, 0xc8, 0xc7, 0xb0, 0xbd, 0xc8, 0xef, 0x3f, 0xd1, 0xea, 0x23, 0x65, 0xd7,
	0x5a, 0x79, 0x65, 0x1a, 0xfd, 0x0a, 0xa0, 0x98, 0xc2, 0x9b, 0xc5, 0x49, 0xd5, 0xad, 0x74, 0x2f,
	0x33, 0x36, 0xaa, 0x47, 0x8d, 0xf3, 0x0b, 0x35, 0xe6, 0x55, 0x5b, 0x85, 0xf8, 0xe8, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf2, 0xbc, 0xb0, 0x8b, 0x0e, 0x0e, 0x00, 0x00,
}
