// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resp.proto

package mproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// =================================  SERVER 收到指令返回 200 pong 消息为1 开始 ===========
// SERVER RESP : MSG_ID 1
// 1.PONG
type PONG struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PONG) Reset()         { *m = PONG{} }
func (m *PONG) String() string { return proto.CompactTextString(m) }
func (*PONG) ProtoMessage()    {}
func (*PONG) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{0}
}

func (m *PONG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PONG.Unmarshal(m, b)
}
func (m *PONG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PONG.Marshal(b, m, deterministic)
}
func (m *PONG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PONG.Merge(m, src)
}
func (m *PONG) XXX_Size() int {
	return xxx_messageInfo_PONG.Size(m)
}
func (m *PONG) XXX_DiscardUnknown() {
	xxx_messageInfo_PONG.DiscardUnknown(m)
}

var xxx_messageInfo_PONG proto.InternalMessageInfo

func (m *PONG) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// SERVER RESP : MSG_ID 200
// 1.登录返回
type RespLogin struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RespLogin) Reset()         { *m = RespLogin{} }
func (m *RespLogin) String() string { return proto.CompactTextString(m) }
func (*RespLogin) ProtoMessage()    {}
func (*RespLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{1}
}

func (m *RespLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespLogin.Unmarshal(m, b)
}
func (m *RespLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespLogin.Marshal(b, m, deterministic)
}
func (m *RespLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespLogin.Merge(m, src)
}
func (m *RespLogin) XXX_Size() int {
	return xxx_messageInfo_RespLogin.Size(m)
}
func (m *RespLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RespLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RespLogin proto.InternalMessageInfo

func (m *RespLogin) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

// SERVER PUSH : MSG_ID 300  // 推送房间类型列表
// 1.房间分类信息推送
type PushRoomClassify struct {
	RoomClassify         []*RoomClassify `protobuf:"bytes,1,rep,name=roomClassify,proto3" json:"roomClassify,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PushRoomClassify) Reset()         { *m = PushRoomClassify{} }
func (m *PushRoomClassify) String() string { return proto.CompactTextString(m) }
func (*PushRoomClassify) ProtoMessage()    {}
func (*PushRoomClassify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{2}
}

func (m *PushRoomClassify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRoomClassify.Unmarshal(m, b)
}
func (m *PushRoomClassify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRoomClassify.Marshal(b, m, deterministic)
}
func (m *PushRoomClassify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRoomClassify.Merge(m, src)
}
func (m *PushRoomClassify) XXX_Size() int {
	return xxx_messageInfo_PushRoomClassify.Size(m)
}
func (m *PushRoomClassify) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRoomClassify.DiscardUnknown(m)
}

var xxx_messageInfo_PushRoomClassify proto.InternalMessageInfo

func (m *PushRoomClassify) GetRoomClassify() []*RoomClassify {
	if m != nil {
		return m.RoomClassify
	}
	return nil
}

// SERVER PUSH : MSG_ID 500  // 服务器断开指令
// 1.断开连接指令
type CloseConn struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseConn) Reset()         { *m = CloseConn{} }
func (m *CloseConn) String() string { return proto.CompactTextString(m) }
func (*CloseConn) ProtoMessage()    {}
func (*CloseConn) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{3}
}

func (m *CloseConn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseConn.Unmarshal(m, b)
}
func (m *CloseConn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseConn.Marshal(b, m, deterministic)
}
func (m *CloseConn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseConn.Merge(m, src)
}
func (m *CloseConn) XXX_Size() int {
	return xxx_messageInfo_CloseConn.Size(m)
}
func (m *CloseConn) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseConn.DiscardUnknown(m)
}

var xxx_messageInfo_CloseConn proto.InternalMessageInfo

func (m *CloseConn) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CloseConn) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// SERVER PUSH : MSG_ID 501  // 服务器错误指令
// 1.服务器错误指令
type ErrMsg struct {
	MsgId                int32    `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrMsg) Reset()         { *m = ErrMsg{} }
func (m *ErrMsg) String() string { return proto.CompactTextString(m) }
func (*ErrMsg) ProtoMessage()    {}
func (*ErrMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{4}
}

func (m *ErrMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrMsg.Unmarshal(m, b)
}
func (m *ErrMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrMsg.Marshal(b, m, deterministic)
}
func (m *ErrMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrMsg.Merge(m, src)
}
func (m *ErrMsg) XXX_Size() int {
	return xxx_messageInfo_ErrMsg.Size(m)
}
func (m *ErrMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ErrMsg proto.InternalMessageInfo

func (m *ErrMsg) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *ErrMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 1. LoginResp   2.PlayerListPush
type PlayerInfo struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`
	PlayerImg            string   `protobuf:"bytes,3,opt,name=playerImg,proto3" json:"playerImg,omitempty"`
	Gold                 float64  `protobuf:"fixed64,4,opt,name=gold,proto3" json:"gold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{5}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PlayerInfo) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *PlayerInfo) GetPlayerImg() string {
	if m != nil {
		return m.PlayerImg
	}
	return ""
}

func (m *PlayerInfo) GetGold() float64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

// RoomClassifyPush
type RoomClassify struct {
	RoomType             int32    `protobuf:"varint,1,opt,name=roomType,proto3" json:"roomType,omitempty"`
	BottomPoint          float64  `protobuf:"fixed64,2,opt,name=bottomPoint,proto3" json:"bottomPoint,omitempty"`
	BottomEnterPoint     float64  `protobuf:"fixed64,3,opt,name=bottomEnterPoint,proto3" json:"bottomEnterPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomClassify) Reset()         { *m = RoomClassify{} }
func (m *RoomClassify) String() string { return proto.CompactTextString(m) }
func (*RoomClassify) ProtoMessage()    {}
func (*RoomClassify) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5365792f61ddff, []int{6}
}

func (m *RoomClassify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomClassify.Unmarshal(m, b)
}
func (m *RoomClassify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomClassify.Marshal(b, m, deterministic)
}
func (m *RoomClassify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomClassify.Merge(m, src)
}
func (m *RoomClassify) XXX_Size() int {
	return xxx_messageInfo_RoomClassify.Size(m)
}
func (m *RoomClassify) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomClassify.DiscardUnknown(m)
}

var xxx_messageInfo_RoomClassify proto.InternalMessageInfo

func (m *RoomClassify) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *RoomClassify) GetBottomPoint() float64 {
	if m != nil {
		return m.BottomPoint
	}
	return 0
}

func (m *RoomClassify) GetBottomEnterPoint() float64 {
	if m != nil {
		return m.BottomEnterPoint
	}
	return 0
}

func init() {
	proto.RegisterType((*PONG)(nil), "mproto.PONG")
	proto.RegisterType((*RespLogin)(nil), "mproto.RespLogin")
	proto.RegisterType((*PushRoomClassify)(nil), "mproto.PushRoomClassify")
	proto.RegisterType((*CloseConn)(nil), "mproto.CloseConn")
	proto.RegisterType((*ErrMsg)(nil), "mproto.ErrMsg")
	proto.RegisterType((*PlayerInfo)(nil), "mproto.PlayerInfo")
	proto.RegisterType((*RoomClassify)(nil), "mproto.RoomClassify")
}

func init() { proto.RegisterFile("resp.proto", fileDescriptor_3c5365792f61ddff) }

var fileDescriptor_3c5365792f61ddff = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x41, 0x6b, 0xf2, 0x40,
	0x10, 0x65, 0xbf, 0xa8, 0x98, 0xd1, 0x83, 0x0c, 0x1e, 0x82, 0x7c, 0x94, 0x90, 0x53, 0xe8, 0x41,
	0x5a, 0x7b, 0xe9, 0xad, 0x07, 0x91, 0x22, 0x58, 0x1b, 0x96, 0xfe, 0x01, 0xad, 0x6b, 0x1a, 0xc8,
	0xee, 0x84, 0xdd, 0x2d, 0xd4, 0xfe, 0xfa, 0x92, 0xdd, 0x18, 0x23, 0xed, 0x69, 0xdf, 0x7b, 0xf3,
	0x66, 0x76, 0xe6, 0x01, 0x68, 0x61, 0xaa, 0x79, 0xa5, 0xc9, 0x12, 0x0e, 0xa4, 0x7b, 0x93, 0x19,
	0xf4, 0xb2, 0xd7, 0xed, 0x33, 0x22, 0xf4, 0x6c, 0x21, 0x45, 0xc4, 0x62, 0x96, 0x06, 0xdc, 0xe1,
	0xe4, 0x09, 0x42, 0x2e, 0x4c, 0xb5, 0xa1, 0xbc, 0x50, 0xb8, 0x00, 0xa8, 0xca, 0xdd, 0x49, 0xe8,
	0xb5, 0x3a, 0x92, 0xb3, 0x8d, 0x16, 0x38, 0xf7, 0x53, 0xe6, 0x59, 0x5b, 0xe1, 0x1d, 0x57, 0xb2,
	0x81, 0x49, 0xf6, 0x69, 0x3e, 0x38, 0x91, 0x5c, 0x96, 0x3b, 0x63, 0x8a, 0xe3, 0x09, 0x1f, 0x61,
	0xac, 0x3b, 0x3c, 0x62, 0x71, 0x90, 0x8e, 0x16, 0xd3, 0xf3, 0xa4, 0xae, 0x97, 0x5f, 0x39, 0x93,
	0x7b, 0x08, 0x97, 0x25, 0x19, 0xb1, 0x24, 0xa5, 0xea, 0x7d, 0xdf, 0xe9, 0xe0, 0xf7, 0xed, 0x73,
	0x87, 0x71, 0x02, 0x81, 0x34, 0x79, 0xf4, 0x2f, 0x66, 0x69, 0xc8, 0x6b, 0x98, 0xdc, 0xc1, 0x60,
	0xa5, 0xf5, 0x8b, 0xc9, 0x71, 0x0a, 0x7d, 0x69, 0xf2, 0xf5, 0xa1, 0x69, 0xf0, 0xe4, 0x8f, 0x8e,
	0x6f, 0x80, 0xcb, 0x31, 0x38, 0x83, 0x61, 0x73, 0x8e, 0x6f, 0x0c, 0x79, 0xcb, 0xf1, 0xe6, 0x1c,
	0xc8, 0x76, 0x27, 0x45, 0x33, 0xa2, 0xa3, 0xe0, 0x7f, 0x08, 0x1b, 0xaf, 0xcc, 0xa3, 0xc0, 0x95,
	0x2f, 0x42, 0xbd, 0x7f, 0x4e, 0xe5, 0x21, 0xea, 0xc5, 0x2c, 0x65, 0xdc, 0xe1, 0xe4, 0x0b, 0xc6,
	0x57, 0x51, 0xcd, 0x60, 0x58, 0x07, 0xf0, 0x76, 0xaa, 0xce, 0x77, 0xb6, 0x1c, 0x63, 0x18, 0xed,
	0xc9, 0x5a, 0x92, 0x19, 0x15, 0xca, 0xba, 0xef, 0x19, 0xef, 0x4a, 0x78, 0x0b, 0x13, 0x4f, 0x57,
	0xca, 0x0a, 0xed, 0x6d, 0x81, 0xb3, 0xfd, 0xd2, 0xf7, 0x03, 0x17, 0xfe, 0xc3, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcf, 0xc9, 0xa6, 0x0d, 0x22, 0x02, 0x00, 0x00,
}
